"""Extra vendors found from deep scraping.

Sources: YC batches, RSAC exhibitors, Black Hat sponsors, Gartner market guides,
Forrester Waves, awesome-security GitHub, Kali tools, MITRE ATT&CK software,
AWS/Azure marketplaces, cybersecurity ETFs, Israeli/EU/India startups, MSSPs,
Cybersecurity Ventures lists, and domain knowledge.
"""

VENDORS_EXTRA = [
    # ===== YC Cybersecurity Startups =====
    "Cyble",
    "Agency",
    "Riot",
    "LogosGuard",
    "Vanta",
    "Snyk",
    "Teleport",
    "Materialize",
    "Panther Labs",
    "Segment",
    "Stytch",
    "WorkOS",
    "PropelAuth",
    "Clerk",
    "Supabase",
    "Resend",
    "Retool",
    "Cal.com",
    "Aptible",
    "Templarbit",
    "Socket.dev",
    "Lumos",
    "Indent",
    "Sym",
    "Crosshatch",
    "Greynoise",
    "Truffle Security",
    "GitGuardian",
    "Bearer",
    "Pixie",
    "Ksoc",
    "Twingate",
    "Tailscale",
    "Boundary",
    "StrongDM",
    "Doppler",
    "Akeyless",
    "Infisical",
    "Oneleet",
    "Paragon",
    "Knocknoc",
    "Piiano",
    "Corgea",
    "Semgrep",
    "Aikido Security",
    "Kodem",
    "Endor Labs",
    "Jit",
    "Armo",
    "Oligo Security",
    "Dazz",
    "Opus Security",
    "Seemplicity",
    "Vulcan Cyber",
    "Silk Security",
    "Lasso Security",
    "Prompt Security",
    "Pillar Security",
    "Aim Security",
    "Robust Intelligence",
    "CalypsoAI",
    "HiddenLayer",
    "Protect AI",
    "Arthur AI",
    "Noma Security",
    "DeepKeep",
    "LLM Guard",
    "Cranium AI",
    "Rebuff AI",
    "7AI",

    # ===== Crunchbase / AngelList Top Funded =====
    "Cyera",
    "Saviynt",
    "Quantinuum",
    "Wiz",
    "Coro",
    "Island",
    "Axonius",
    "Abnormal Security",
    "Orca Security",
    "Netskope",
    "Lacework",
    "Snyk",
    "SentinelOne",
    "Arctic Wolf",
    "Dragos",
    "Expel",
    "SafeBreach",
    "Torq",
    "Tines",
    "Drata",
    "Secureframe",
    "Sprinto",
    "Vanta",
    "Thoropass",
    "Laika",
    "Scrut Automation",
    "Scrut",
    "AuditBoard",
    "LogicGate",
    "Hyperproof",
    "Anecdotes",
    "RegScale",
    "Compyl",
    "CyberSaint",
    "Strike Graph",
    "Tugboat Logic",
    "StandardFusion",
    "TrustCloud",
    "ZenGRC",
    "Reciprocity",
    "Conveyor",
    "SafeBase",
    "Scytale",
    "Censys",
    "GreyNoise",
    "Recorded Future",
    "Flashpoint",
    "Intel 471",
    "ThreatConnect",
    "EclecticIQ",
    "Mandiant",
    "SOCRadar",
    "SpyCloud",
    "ZeroFox",
    "Cyble",
    "Intezer",
    "ThreatQuotient",
    "DomainTools",
    "SecurityTrails",
    "RiskIQ",
    "Shodan",
    "VirusTotal",
    "Group-IB",
    "KELA",
    "Team Cymru",

    # ===== RSAC 2024/2025 Exhibitors =====
    "12Port",
    "1Password",
    "Absolute Security",
    "Acalvio Technologies",
    "Accedere",
    "Action1",
    "Aembit",
    "Akamai Technologies",
    "Alkira",
    "Anomali",
    "AppViewX",
    "Arista Networks",
    "Armis",
    "AttackIQ",
    "Axonius",
    "BackBox",
    "Bitwarden",
    "Black Kite",
    "Blumira",
    "BOD Security",
    "Booz Allen Hamilton",
    "Brinqa",
    "Bugcrowd",
    "CardinalOps",
    "Cavelo",
    "Cequence Security",
    "Cisco",
    "Claroty",
    "Cleafy",
    "Cloudflare",
    "Cobalt",
    "Cofense",
    "ColorTokens",
    "ConductorOne",
    "Constella Intelligence",
    "Contrast Security",
    "Corelight",
    "CrowdStrike",
    "CyberArk",
    "CyCognito",
    "Cymulate",
    "D3 Security",
    "Darktrace",
    "DataDome",
    "Deep Instinct",
    "Delinea",
    "DigiCert",
    "DNSFilter",
    "Eclypsium",
    "Elisity",
    "Entrust",
    "Ermetic",
    "eSentire",
    "Exabeam",
    "ExtraHop",
    "F5",
    "Feitian Technologies",
    "FireEye",
    "FireMon",
    "Flashpoint",
    "Forescout",
    "Forcepoint",
    "Fortinet",
    "Garland Technology",
    "Gigamon",
    "GitLab",
    "Google Cloud",
    "Grip Security",
    "Guardicore",
    "HackerOne",
    "Halcyon",
    "Hillstone Networks",
    "Horizon3.ai",
    "HUMAN Security",
    "Hunters",
    "Huntress",
    "IBM Security",
    "Illumio",
    "Immersive Labs",
    "Imperva",
    "Infoblox",
    "Ivanti",
    "Jamf",
    "Juniper Networks",
    "JupiterOne",
    "Kasada",
    "Keeper Security",
    "Keyfactor",
    "KnowBe4",
    "Lacework",
    "LevelBlue",
    "Lightspin",
    "LogRhythm",
    "Lookout",
    "Lumu Technologies",
    "Mandiant",
    "Mend.io",
    "Menlo Security",
    "Microsoft",
    "Mimecast",
    "Minerva Labs",
    "Mocana",
    "Morphisec",
    "Neowise",
    "NetSPI",
    "Netskope",
    "NeuVector",
    "Nightfall AI",
    "NinjaOne",
    "Noname Security",
    "Normalyze",
    "Nozomi Networks",
    "Nucleus Security",
    "Obsidian Security",
    "Okta",
    "OneTrust",
    "Orca Security",
    "Oort",
    "OPSWAT",
    "Ostorlab",
    "OX Security",
    "PacketViper",
    "Palo Alto Networks",
    "Pentera",
    "Perception Point",
    "PerimeterX",
    "Permiso",
    "Picus Security",
    "PlexTrac",
    "Portnox",
    "Proofpoint",
    "Qualys",
    "Radware",
    "Rapid7",
    "Recorded Future",
    "Red Canary",
    "Rezilion",
    "Ridge Security",
    "RiskRecon",
    "Rubrik",
    "Runzero",
    "SafeBreach",
    "Sailpoint",
    "Salt Security",
    "SANS Institute",
    "Saviynt",
    "SecurityScorecard",
    "Secureworks",
    "Securonix",
    "Semperis",
    "SentinelOne",
    "Sevco Security",
    "Silverfort",
    "Skybox Security",
    "Snyk",
    "Sonatype",
    "Sophos",
    "Splunk",
    "StackHawk",
    "Sumo Logic",
    "Swimlane",
    "Synack",
    "Sysdig",
    "Talon Cyber Security",
    "Tanium",
    "Tenable",
    "ThreatLocker",
    "ThreatX",
    "Tigera",
    "Torq",
    "Traceable AI",
    "Trellix",
    "Trend Micro",
    "Tufin",
    "TXOne Networks",
    "Uptycs",
    "Varonis",
    "Vectra AI",
    "Venafi",
    "Versa Networks",
    "Viavi Solutions",
    "Wallarm",
    "WatchGuard",
    "Wing Security",
    "Wiz",
    "XM Cyber",
    "Zafran",
    "Zero Networks",
    "Zimperium",
    "Zscaler",

    # ===== Gartner Market Guide Vendors =====
    "Orange Cyberdefense",
    "Integrity360",
    "Eviden",
    "Wipro",
    "HCL Technologies",
    "DXC Technology",
    "Capgemini",
    "Cognizant",
    "Tech Mahindra",
    "LTIMindtree",
    "Mphasis",
    "NTT Data",
    "Fujitsu",
    "Atos",
    "CGI",
    "Unisys",
    "BAE Systems",
    "Thales",
    "Raytheon",
    "Northrop Grumman",
    "General Dynamics",
    "L3Harris",
    "SAIC",
    "Leidos",
    "Booz Allen Hamilton",
    "Lockheed Martin",
    "Boeing",
    "ManTech",
    "Perspecta",

    # ===== Forrester Wave Vendors =====
    "CrowdStrike",
    "Elastic",
    "Exabeam",
    "Google",
    "Microsoft",
    "Palo Alto Networks",
    "Rapid7",
    "Securonix",
    "Splunk",
    "Sumo Logic",
    "SecurityScorecard",
    "BitSight",
    "Black Kite",
    "RiskRecon",
    "UpGuard",
    "Panorays",
    "Safe Security",
    "Kovrr",
    "RiskLens",
    "Axio",
    "Trail of Bits",

    # ===== Cybersecurity 500 / Hot 150 =====
    "SentinelOne",
    "Zscaler",
    "CrowdStrike",
    "Cloudflare",
    "BlackBerry",
    "Fortinet",
    "Palo Alto Networks",
    "KnowBe4",
    "Telos Corporation",
    "Telos",
    "SonicWall",
    "Carbon Black",
    "Webroot",
    "CrowdStrike",
    "Cylance",
    "Rapid7",
    "Qualys",
    "Sailpoint",
    "Varonis",
    "Proofpoint",
    "Mimecast",
    "Barracuda Networks",
    "WatchGuard",
    "Sophos",
    "ESET",
    "Trend Micro",
    "McAfee",
    "Norton",
    "Kaspersky",
    "Bitdefender",
    "Malwarebytes",
    "F-Secure",
    "WithSecure",
    "Emsisoft",
    "Comodo",
    "ClamAV",
    "Avast",
    "AVG Technologies",
    "Avira",
    "G Data",
    "BullGuard",
    "Panda Security",
    "Vipre",
    "Webroot",
    "ZoneAlarm",
    "Binarly",
    "Dope Security",
    "Lakera",
    "Radiant Security",

    # ===== Top MSSPs =====
    "Trustwave",
    "IBM Security",
    "Accenture Security",
    "Verizon",
    "AT&T Cybersecurity",
    "LevelBlue",
    "SecureWorks",
    "eSentire",
    "Arctic Wolf",
    "Expel",
    "Red Canary",
    "Binary Defense",
    "BlueVoyant",
    "Deepwatch",
    "Nuspire",
    "Proficio",
    "Avertium",
    "Critical Start",
    "Open Systems",
    "UnderDefense",
    "Alert Logic",
    "Optiv",
    "Masergy",
    "NTT Security",
    "Herjavec Group",
    "Kyndryl",
    "CrowdStrike Falcon Complete",
    "Sophos MDR",
    "ReliaQuest",
    "Kudelski Security",
    "Dataprise",
    "DataEndure",
    "Netsurion",
    "Gradient Cyber",
    "Eventus Security",
    "Cyflare",
    "ConnectWise",
    "Todyl",
    "Blackpoint Cyber",
    "Huntsman Security",
    "Securitas",
    "Cipher",
    "Prosegur",
    "GoSecure",
    "Cyderes",
    "Difenda",
    "Armor",
    "ControlScan",
    "TrustNet",
    "Nettitude",
    "Solutionary",
    "M.A. Polce",
    "CyberProof",
    "Tata Communications",
    "Verizon Business Security",
    "BT Security",
    "Lumen Technologies",
    "Windstream Enterprise",
    "CenturyLink",
    "GTT Communications",
    "TPx Communications",
    "Masergy Communications",
    "Cato Networks",
    "Perimeter 81",

    # ===== Israeli Cybersecurity Companies =====
    "Check Point",
    "CyberArk",
    "Wiz",
    "Snyk",
    "Cyera",
    "Island",
    "Axonius",
    "Silverfort",
    "Aqua Security",
    "Torq",
    "Wing Security",
    "Noma Security",
    "Token Security",
    "Gomboc",
    "Descope",
    "Astrix Security",
    "NSO Group",
    "Radware",
    "Riskified",
    "Talon Cyber Security",
    "Transmit Security",
    "Argus Cyber Security",
    "Carbyne",
    "Cynet",
    "CYREN",
    "Odix",
    "Quadream",
    "Armis",
    "Claroty",
    "SCADAfence",
    "Pentera",
    "XM Cyber",
    "Cato Networks",
    "Illumio",
    "SafeBreach",
    "Cymulate",
    "Hunters",
    "Salt Security",
    "Noname Security",
    "Orca Security",
    "Ermetic",
    "Lightspin",
    "Dig Security",
    "Laminar",
    "Flow Security",
    "Polar Security",
    "Sentra",
    "Normalyze",
    "Eureka Security",
    "Oasis Security",
    "Oleria",
    "Silverfort",
    "Semperis",
    "Authomize",
    "Adaptive Shield",
    "Valence Security",
    "DoControl",
    "Grip Security",
    "Obsidian Security",
    "Suridata",
    "Savvy Security",
    "Nudge Security",
    "Reco",
    "AppOmni",
    "Atmosec",
    "Zafran",
    "Seraphic",
    "Conceal",
    "Red Access",
    "SOOS",
    "Enso Security",
    "Apiiro",
    "Ox Security",
    "Legit Security",
    "Cycode",
    "Checkmarx",
    "Mobb",
    "Kodem",
    "Backslash Security",
    "Jit",
    "Dazz",
    "Opus Security",
    "Seemplicity",
    "Silk Security",
    "Vulcan Cyber",
    "Ermetic",
    "AccuKnox",
    "Imperva",
    "Guardicore",
    "TrapX Security",
    "Illusive Networks",
    "CounterCraft",
    "Acalvio",
    "Deep Instinct",
    "Morphisec",
    "Minerva Labs",
    "Perception Point",
    "IRONSCALES",
    "Abnormal Security",
    "Intezer",
    "Cybereason",
    "Stellar Cyber",
    "Lasso Security",
    "Prompt Security",
    "Aim Security",
    "Pillar Security",
    "Zenity",
    "Miggo",
    "Sweet Security",
    "Stream Security",
    "Upwind",
    "Mitiga",
    "CardinalOps",
    "Anecdotes",
    "Panorays",
    "Safe Security",
    "CyberInt",
    "IntSights",
    "Sixgill",
    "Cybersixgill",
    "Cyberbit",
    "Pcysys",
    "PlaxidityX",
    "Karamba Security",
    "C2A Security",
    "Upstream Security",
    "Regula Forensics",
    "SecBI",
    "ThetaRay",
    "BioCatch",
    "Forter",
    "Riskified",
    "Socure",
    "Secret Double Octopus",
    "Beyond Security",
    "Votiro",
    "Perimeter 81",
    "ZeroFox",
    "Sygnia",
    "CYE",
    "Veriti",
    "Vicarius",
    "Cynomi",
    "Elitium",

    # ===== Indian Cybersecurity Companies =====
    "Tata Consultancy Services",
    "TCS",
    "Infosys",
    "Wipro",
    "HCL Technologies",
    "Tech Mahindra",
    "QualySec",
    "Beagle Security",
    "Vault Infosec",
    "digiALERT",
    "GRAMAX CyberTech",
    "WiJungle",
    "InstaSafe",
    "TAC Security",
    "Lucideus",
    "Safe Security",
    "Sequretek",
    "Data Resolve",
    "Kratikal",
    "Pristine InfoSolutions",
    "SISA",
    "Payatu",
    "iValue InfoSolutions",
    "Netrika Consulting",
    "K7 Security",
    "Quick Heal",
    "Seqrite",
    "Marg ERP",
    "Cyberoam",
    "eScan",
    "Net Protector",
    "Druva",
    "Paladion",
    "Aujas Cybersecurity",
    "iSec Services",

    # ===== European Cybersecurity Startups =====
    "Dattak",
    "Eye Security",
    "Filigran",
    "Push Security",
    "Evervault",
    "Tines",
    "GoodAccess",
    "Passbolt",
    "Tessian",
    "Darktrace",
    "Snyk",
    "Privitar",
    "Callsign",
    "Onfido",
    "Onfido",
    "Featurespace",
    "Thought Machine",
    "Hack The Box",
    "Immersive Labs",
    "Hadrian",
    "EclecticIQ",
    "Midnight Blue",
    "HarfangLab",
    "Sekoia",
    "Tehtris",
    "Stormshield",
    "Gatewatcher",
    "Pradeo",
    "Yogosha",
    "YesWeHack",
    "Quarkslab",
    "CrowdSec",
    "GitGuardian",
    "Alsid",
    "Vade",
    "Mailinblack",
    "Wallix",
    "Outpost24",
    "Detectify",
    "Truesec",
    "Clavister",
    "F-Secure",
    "WithSecure",
    "SSH Communications",
    "Baffin Bay Networks",
    "Yubico",
    "Hoxhunt",
    "Nixu",
    "BaseN",
    "Arctic Security",
    "Cyberwatch",
    "ESET",
    "Avast",
    "Promon",
    "River Security",
    "Mnemonic",
    "Nclose",
    "SmartDec",
    "Kaspersky",
    "Acronis",
    "Proton",
    "Threema",
    "Wire",
    "Hornetsecurity",
    "G Data",
    "Rohde & Schwarz Cybersecurity",
    "Genua",
    "secunet Security Networks",
    "Virtual Solution",
    "Myra Security",
    "Link11",
    "DriveLock",
    "OTARIS",
    "Perseus Technologies",
    "SoSafe",
    "IT-Seal",
    "CyberCompare",
    "Lywand",
    "Enginsight",
    "Greenbone Networks",
    "Bitdefender",
    "Thales",
    "Airbus CyberSecurity",
    "Atos",
    "BT Security",
    "NCC Group",
    "Sopra Steria",
    "Capgemini",
    "Orange Cyberdefense",
    "Kudelski Security",
    "Swisscom Security",
    "T-Systems",
    "Deutsche Telekom Security",
    "Vodafone Business Security",

    # ===== Kali Linux Tools / Security Tools =====
    "Nmap",
    "Wireshark",
    "Metasploit",
    "Burp Suite",
    "John the Ripper",
    "Hydra",
    "Aircrack-ng",
    "Kismet",
    "Hashcat",
    "SQLMap",
    "Nikto",
    "Dirb",
    "DirBuster",
    "Gobuster",
    "Wfuzz",
    "Ffuf",
    "Amass",
    "Subfinder",
    "Masscan",
    "Rustscan",
    "Naabu",
    "Httpx",
    "Nuclei",
    "Maltego",
    "Recon-ng",
    "theHarvester",
    "SpiderFoot",
    "Shodan",
    "Censys",
    "Shodan CLI",
    "Responder",
    "CrackMapExec",
    "Impacket",
    "BloodHound",
    "PowerSploit",
    "Empire",
    "Covenant",
    "Sliver",
    "Cobalt Strike",
    "Havoc",
    "Brute Ratel",
    "Mythic",
    "Merlin",
    "PoshC2",
    "Koadic",
    "BeEF",
    "Social Engineering Toolkit",
    "SET",
    "Gophish",
    "Evilginx",
    "Modlishka",
    "King Phisher",
    "Volatility",
    "Autopsy",
    "Sleuth Kit",
    "FTK Imager",
    "CAINE",
    "SIFT",
    "REMnux",
    "Ghidra",
    "IDA Pro",
    "Radare2",
    "x64dbg",
    "OllyDbg",
    "Binary Ninja",
    "Cutter",
    "Rizin",
    "YARA",
    "ClamAV",
    "Snort",
    "Suricata",
    "Zeek",
    "Bro",
    "Arkime",
    "Moloch",
    "NetworkMiner",
    "Ettercap",
    "Bettercap",
    "MITMProxy",
    "SSLStrip",
    "Wpscan",
    "Joomscan",
    "CMSMap",
    "Droopescan",
    "Skipfish",
    "Arachni",
    "w3af",
    "Vega",
    "Wapiti",
    "ZAP",
    "OpenVAS",
    "Nessus",
    "Nexpose",
    "Lynis",
    "OpenSCAP",
    "LinPEAS",
    "WinPEAS",
    "Mimikatz",
    "LaZagne",
    "Rubeus",
    "Certify",
    "Certipy",
    "ADCSKiller",
    "Seatbelt",
    "SharpHound",
    "PingCastle",
    "Testssl.sh",
    "SSLScan",
    "SSLyze",
    "TLS-Scanner",
    "Scapy",
    "Hping3",
    "Netcat",
    "Socat",
    "TCPDump",
    "Tshark",
    "Fierce",
    "DNSRecon",
    "DNSEnum",
    "Sublist3r",
    "Altdns",
    "MassDNS",
    "Puredns",
    "Httprobe",
    "Waybackurls",
    "Gau",
    "Katana",
    "Crawley",
    "Feroxbuster",
    "Arjun",
    "ParamSpider",
    "Dalfox",
    "XSStrike",
    "Commix",
    "NoSQLMap",
    "CeWL",
    "Crunch",
    "Medusa",
    "Patator",
    "Crowbar",
    "THC-Hydra",
    "Ophcrack",
    "RainbowCrack",
    "Pipal",
    "Chntpw",
    "Enum4linux",
    "SMBMap",
    "Smbclient",
    "Rpcclient",
    "LDAPSearch",
    "Kerbrute",
    "GetNPUsers",
    "GetUserSPNs",
    "Secretsdump",
    "Proxychains",
    "Chisel",
    "Ligolo",
    "SSHuttle",
    "Socat",

    # ===== MITRE ATT&CK Software / Tools =====
    "Caldera",
    "ATT&CK Navigator",
    "ATT&CK Workbench",
    "Atomic Red Team",
    "Red Canary",
    "Metta",
    "Sandbox Scryer",
    "Decider",
    "Vectr",
    "DeTT&CT",
    "SIGMA",
    "Unfetter",

    # ===== Cybersecurity ETF Holdings =====
    # CIBR ETF
    "Cisco Systems",
    "Infosys",
    "Broadcom",
    "Palo Alto Networks",
    "CrowdStrike",
    "Thales",
    "Akamai Technologies",
    "F5",
    "Fortinet",
    "Leidos",
    "Zscaler",
    "CyberArk",
    "Okta",
    "Check Point",
    "Juniper Networks",
    "Varonis Systems",
    "Qualys",
    "Rapid7",
    "Tenable",
    "SentinelOne",
    "Booz Allen Hamilton",
    "CommScope",
    "OneSpan",
    "Telos",
    "Radware",
    "A10 Networks",
    "SecureWorks",
    "Ping Identity",
    "ForgeRock",
    "SailPoint Technologies",
    "Mimecast",
    "Proofpoint",
    "Sailpoint",
    "Knowbe4",

    # HACK ETF
    "Northrop Grumman",
    "General Dynamics",
    "Fastly",
    "Cloudflare",
    "Mandiant",
    "Commvault",
    "NetScout Systems",
    "Ribbon Communications",
    "Calix",
    "Limelight Networks",
    "Mitek Systems",
    "CalAmp",
    "Absolute Software",
    "Identiv",
    "Parsons Corporation",
    "CACI International",
    "ICF International",

    # BUG ETF
    "Accton Technology",
    "Trend Micro",
    "Sophos",
    "NortonLifeLock",
    "Gen Digital",

    # IHAK ETF
    "Splunk",
    "Datadog",
    "Elastic",

    # ===== Black Hat Sponsors / Exhibitors =====
    "Accenture",
    "Amazon Web Services",
    "AWS",
    "CrowdStrike",
    "Darktrace",
    "Dell Technologies",
    "Fortinet",
    "Google Cloud",
    "IBM",
    "Intel",
    "Mandiant",
    "Microsoft",
    "NVIDIA",
    "Palo Alto Networks",
    "Samsung",
    "ServiceNow",
    "Splunk",
    "Synopsys",
    "Tanium",
    "Tenable",
    "Trellix",
    "Trend Micro",
    "VMware",
    "Wiz",
    "Zimperium",
    "Bitdefender",
    "Black Duck",
    "Bugcrowd",
    "Checkmarx",
    "CloudStrike",
    "Contrast Security",
    "Core Security",
    "Cybereason",
    "Deep Instinct",
    "Eclypsium",
    "Endor Labs",
    "Exabeam",
    "Flashpoint",
    "Fortify",
    "HackerOne",
    "Hunters",
    "Imperva",
    "IONIX",
    "Kaspersky",
    "LastPass",
    "Malwarebytes",
    "Netskope",
    "Okta",
    "OWASP",
    "Qualys",
    "Radware",
    "Recorded Future",
    "SANS",
    "SecurityScorecard",
    "SentinelOne",
    "Snyk",
    "Sophos",
    "StackHawk",
    "Synack",
    "ThreatLocker",
    "Trustwave",
    "Veracode",
    "Wiz",
    "Zscaler",

    # ===== Security Onion Integrated Tools =====
    "Security Onion",
    "Elasticsearch",
    "Logstash",
    "Kibana",
    "Suricata",
    "Zeek",
    "Wazuh",
    "Stenographer",
    "CyberChef",
    "NetworkMiner",
    "osquery",
    "Elastic Agent",
    "Elastic Fleet",
    "OpenCanary",
    "TheHive",
    "Cortex",
    "Sigma",
    "Strelka",
    "Grafana",

    # ===== OWASP Tools / Projects =====
    "OWASP ZAP",
    "OWASP Dependency-Check",
    "OWASP ModSecurity CRS",
    "OWASP OWTF",
    "OWASP Juice Shop",
    "OWASP WebGoat",
    "OWASP SAMM",
    "OWASP ASVS",
    "OWASP Amass",
    "OWASP Defectdojo",
    "DefectDojo",
    "OWASP Threat Dragon",
    "OWASP SecurityRAT",
    "OWASP Cornucopia",
    "OWASP Cheat Sheet Series",
    "OWASP Testing Guide",
    "OWASP Mobile Security",
    "OWASP API Security",
    "OWASP Top Ten",
    "OWASP WSTG",

    # ===== AWS Marketplace Security Vendors =====
    "Fortinet",
    "CrowdStrike",
    "Trend Micro",
    "Palo Alto Networks",
    "Check Point",
    "Barracuda Networks",
    "Sophos",
    "F5 Networks",
    "Imperva",
    "Alert Logic",
    "Sumo Logic",
    "Splunk",
    "Rapid7",
    "Qualys",
    "Tenable",
    "Symantec",
    "McAfee",
    "Carbon Black",
    "CrowdStrike",
    "Dome9",
    "CloudPassage",
    "Evident.io",
    "RedLock",
    "Armor Defense",
    "Halo Security",
    "Threat Stack",
    "Signal Sciences",
    "Guardicore",
    "Twistlock",
    "Aqua Security",
    "Lacework",
    "Sysdig",
    "Datadog",
    "New Relic",
    "Dynatrace",
    "AppDynamics",
    "HashiCorp",
    "Terraform",
    "Vault",
    "Consul",
    "Boundary",

    # ===== Azure Marketplace Security Vendors =====
    "Microsoft",
    "Barracuda",
    "ESET",
    "Orca Security",
    "Check Point",
    "Fortinet",
    "Palo Alto Networks",
    "Cisco",
    "Trend Micro",
    "SentinelOne",
    "CrowdStrike",
    "Sophos",
    "Qualys",
    "Tenable",
    "Rapid7",
    "Veritas",
    "Commvault",
    "Cohesity",
    "Rubrik",
    "Veeam",

    # ===== Infrastructure Providers =====
    "AWS",
    "Amazon Web Services",
    "Microsoft Azure",
    "Google Cloud Platform",
    "GCP",
    "DigitalOcean",
    "Linode",
    "Vultr",
    "OVH",
    "OVHcloud",
    "Hetzner",
    "Equinix",
    "Rackspace",
    "Oracle Cloud",
    "IBM Cloud",
    "Alibaba Cloud",
    "Tencent Cloud",
    "Huawei Cloud",
    "Scaleway",
    "UpCloud",
    "Kamatera",

    # ===== CDN / DDoS Protection =====
    "Cloudflare",
    "Akamai",
    "Fastly",
    "Imperva",
    "Sucuri",
    "AWS Shield",
    "Azure DDoS Protection",
    "KeyCDN",
    "StackPath",
    "Limelight Networks",
    "Edgecast",
    "Verizon Digital Media",
    "BunnyCDN",
    "Section",
    "ArvanCloud",

    # ===== DNS Security =====
    "Cisco Umbrella",
    "Infoblox",
    "BlueCat",
    "EfficientIP",
    "DNSFilter",
    "NextDNS",
    "Quad9",
    "CleanBrowsing",
    "SafeDNS",
    "Neustar",
    "Comodo Secure DNS",
    "Yandex DNS",
    "AdGuard DNS",
    "Pi-hole",
    "PowerDNS",
    "Knot DNS",
    "Unbound",
    "BIND",

    # ===== VPN Providers =====
    "NordVPN",
    "NordLayer",
    "ExpressVPN",
    "Mullvad",
    "WireGuard",
    "OpenVPN",
    "Tailscale",
    "ZeroTier",
    "Proton VPN",
    "Surfshark",
    "CyberGhost",
    "Private Internet Access",
    "IPVanish",
    "TunnelBear",
    "Windscribe",
    "IVPN",
    "Hotspot Shield",
    "StrongVPN",
    "VyprVPN",
    "HideMyAss",
    "PureVPN",
    "TorGuard",
    "AirVPN",
    "Astrill",
    "Perimeter 81",
    "Twingate",
    "Cloudflare WARP",
    "Zscaler Private Access",
    "Cisco AnyConnect",
    "GlobalProtect",
    "Fortinet FortiClient VPN",
    "SonicWall VPN",
    "Pulse Secure VPN",
    "Citrix Gateway VPN",

    # ===== Enterprise Browsers =====
    "Island",
    "Talon Cyber Security",
    "Seraphic",
    "Menlo Security",
    "Authentic8",
    "Conceal",
    "LayerX",
    "Puffin Secure Browser",
    "Citrix Secure Browser",
    "Garrison",
    "SURF Security",
    "Mammoth Cyber",

    # ===== Physical Security =====
    "Verkada",
    "Rhombus",
    "Avigilon",
    "Genetec",
    "Milestone Systems",
    "Axis Communications",
    "Hanwha Vision",
    "Hikvision",
    "Dahua Technology",
    "Bosch Security",
    "Honeywell Security",
    "Johnson Controls",
    "Tyco",
    "ADT",
    "Brivo",
    "Eagle Eye Networks",
    "Alarm.com",
    "Openpath",
    "Latch",
    "Proxy",
    "STANLEY Security",
    "Securitas",
    "G4S",
    "Allied Universal",
    "Prosegur",

    # ===== Authentication Hardware =====
    "Yubico",
    "YubiKey",
    "Feitian Technologies",
    "Token2",
    "Nitrokey",
    "SoloKeys",
    "Thetis",
    "HyperFIDO",
    "GoTrust",
    "AuthenTrend",
    "eWBM",
    "Thales",
    "Gemalto",
    "RSA SecurID",
    "Duo Security",
    "HID Global",
    "Idemia",
    "NXP Semiconductors",
    "Infineon",
    "STMicroelectronics",

    # ===== Compliance Platforms =====
    "Drata",
    "Vanta",
    "Secureframe",
    "Sprinto",
    "Scrut",
    "Thoropass",
    "AuditBoard",
    "LogicGate",
    "OneTrust",
    "TrustArc",
    "BigID",
    "Transcend",
    "Privado",
    "Ethyca",
    "Osano",
    "Ketch",
    "DataGrail",
    "Securiti.ai",
    "Privacera",
    "WireWheel",
    "Cookiebot",
    "CookieYes",
    "Termly",
    "iubenda",
    "Didomi",
    "Usercentrics",
    "consent.io",
    "CompliancePoint",
    "A-LIGN",
    "Coalfire",
    "Schellman",
    "Prescient Assurance",
    "Johanson Group",

    # ===== ITSM with Security =====
    "ServiceNow",
    "Jira",
    "Atlassian",
    "Freshservice",
    "Freshworks",
    "Zendesk",
    "PagerDuty",
    "OpsGenie",
    "xMatters",
    "Rootly",
    "incident.io",
    "FireHydrant",
    "Blameless",
    "Shoreline",
    "Squadcast",
    "VictorOps",
    "BigPanda",
    "Moogsoft",
    "ScienceLogic",
    "LogicMonitor",
    "Dynatrace",
    "ConnectWise",
    "Datto RMM",
    "Kaseya",
    "NinjaRMM",
    "Atera",
    "SyncroMSP",
    "Auvik",
    "Liongard",

    # ===== Code Security =====
    "Snyk",
    "Veracode",
    "Checkmarx",
    "SonarQube",
    "SonarSource",
    "Semgrep",
    "CodeQL",
    "Bandit",
    "Brakeman",
    "gosec",
    "Safety",
    "pip-audit",
    "npm audit",
    "Dependabot",
    "Renovate",
    "Mend",
    "WhiteSource",
    "Synopsys",
    "Black Duck",
    "FOSSA",
    "Tidelift",
    "GitHub Advanced Security",
    "GitLab Security",
    "Fortify",
    "Coverity",
    "Codacy",
    "DeepSource",
    "Codiga",
    "Sourcegraph",
    "Qwiet AI",
    "ShiftLeft",
    "Contrast Security",
    "Invicti",
    "Acunetix",
    "Netsparker",
    "HCL AppScan",
    "PortSwigger",
    "StackHawk",
    "Probely",
    "Bearer",
    "Aikido Security",
    "GitGuardian",
    "TruffleHog",
    "Gitleaks",
    "detect-secrets",
    "SpectralOps",

    # ===== Container / K8s Security =====
    "Aqua Security",
    "Sysdig",
    "Falco",
    "Trivy",
    "Grype",
    "Anchore",
    "Twistlock",
    "NeuVector",
    "StackRox",
    "ARMO",
    "Kubescape",
    "Fairwinds",
    "Datree",
    "Kyverno",
    "OPA",
    "Gatekeeper",
    "Calico",
    "Cilium",
    "Tigera",
    "Isovalent",
    "KubeLinter",
    "Mondoo",
    "Chainguard",
    "Slim.ai",
    "Snyk Container",
    "Docker Scout",
    "Wiz Runtime",
    "Prisma Cloud",
    "Lacework",
    "CrowdStrike Cloud",

    # ===== Observability with Security =====
    "Datadog",
    "Splunk",
    "New Relic",
    "Dynatrace",
    "Grafana",
    "Elastic",
    "Sumo Logic",
    "Cribl",
    "Mezmo",
    "Chronosphere",
    "Honeycomb",
    "Lightstep",
    "Observe Inc",
    "AppDynamics",
    "Instana",
    "SignalFx",
    "Wavefront",
    "Humio",
    "LogDNA",
    "Loki",
    "Fluentd",
    "Fluentbit",
    "Vector",
    "Promtail",
    "Prometheus",
    "Thanos",
    "VictoriaMetrics",
    "Mimir",
    "Tempo",
    "Jaeger",
    "Zipkin",

    # ===== Anti-Fraud =====
    "Sift",
    "Forter",
    "Riskified",
    "Kount",
    "Sardine",
    "Unit21",
    "Alloy",
    "Socure",
    "Jumio",
    "Onfido",
    "Persona",
    "Veriff",
    "Telesign",
    "Prove",
    "Ekata",
    "LexisNexis Risk Solutions",
    "TransUnion",
    "Experian",
    "Equifax",
    "NICE Actimize",
    "Featurespace",
    "Feedzai",
    "ComplyAdvantage",
    "Chainalysis",
    "Elliptic",
    "TRM Labs",
    "Refinitiv",
    "Dow Jones Risk & Compliance",
    "Trulioo",
    "Sumsub",
    "Shufti Pro",
    "IDnow",
    "Signicat",
    "Iovation",
    "ThreatMetrix",
    "Arkose Labs",
    "DataDome",
    "PerimeterX",
    "HUMAN Security",
    "Shape Security",
    "BioCatch",
    "Castle",
    "Fingerprint",
    "FingerprintJS",
    "Deduce",
    "DataVisor",

    # ===== Crypto / Blockchain Security =====
    "Chainalysis",
    "Elliptic",
    "TRM Labs",
    "CertiK",
    "OpenZeppelin",
    "Immunefi",
    "Forta",
    "Hexagate",
    "Halborn",
    "Trail of Bits",
    "Consensys Diligence",
    "Quantstamp",
    "PeckShield",
    "SlowMist",
    "BlockSec",
    "Ancilia",
    "Dedaub",
    "Spearbit",
    "Code4rena",
    "Sherlock",
    "Hacken",
    "Certora",
    "Runtime Verification",
    "Fireblocks",
    "BitGo",
    "Copper",
    "Anchorage",
    "Cobo",
    "Ledger Enterprise",
    "Trezor",
    "SafePal",
    "Gnosis Safe",
    "Safe",
    "MPC Alliance",
    "Curv",
    "Qredo",
    "Sepior",
    "Unbound Security",

    # ===== Password Managers =====
    "1Password",
    "LastPass",
    "Bitwarden",
    "Dashlane",
    "Keeper",
    "NordPass",
    "RoboForm",
    "Sticky Password",
    "Enpass",
    "KeePass",
    "KeePassXC",
    "mSecure",
    "Zoho Vault",
    "ManageEngine Password Manager Pro",
    "Pleasant Password Server",
    "Thycotic Secret Server",
    "CyberArk Vault",
    "BeyondTrust Password Safe",
    "Delinea",
    "Devolutions",
    "Passbolt",
    "Psono",
    "Teampass",
    "Vaultwarden",

    # ===== Email Security (Extended) =====
    "Proofpoint",
    "Mimecast",
    "Barracuda",
    "Abnormal Security",
    "Tessian",
    "Material Security",
    "IRONSCALES",
    "Cofense",
    "Egress",
    "Trustifi",
    "Perception Point",
    "Sublime Security",
    "Avanan",
    "Area 1 Security",
    "Cloudflare Area 1",
    "Hornetsecurity",
    "Libraesva",
    "SpamTitan",
    "TitanHQ",
    "Mailinblack",
    "Retarus",
    "Vade",
    "Zerospam",
    "Clearswift",
    "Vircom",
    "Hoxhunt",
    "KnowBe4",
    "Ninjio",
    "CybSafe",
    "Living Security",
    "Terranova Security",
    "Wombat Security",
    "Infosec IQ",
    "SoSafe",
    "Curricula",
    "Hook Security",
    "Riot Security",
    "Keepnet Labs",
    "Phished",
    "Proofpoint Security Awareness",
    "SANS Security Awareness",

    # ===== Threat Modeling =====
    "IriusRisk",
    "ThreatModeler",
    "Cairis",
    "Microsoft Threat Modeling Tool",
    "OWASP Threat Dragon",
    "Pytm",
    "Threagile",
    "STRIDE",

    # ===== Security Orchestration / Automation =====
    "Tines",
    "Torq",
    "Blink",
    "Swimlane",
    "Cortex XSOAR",
    "Splunk SOAR",
    "IBM QRadar SOAR",
    "Fortinet FortiSOAR",
    "D3 Security",
    "Cyware",
    "TheHive",
    "Shuffle",
    "Siemplify",
    "Demisto",
    "Phantom",
    "Resilient",

    # ===== Bug Bounty Platforms =====
    "HackerOne",
    "Bugcrowd",
    "Synack",
    "Cobalt",
    "YesWeHack",
    "Intigriti",
    "Open Bug Bounty",
    "Detectify",
    "Yogosha",
    "HackenProof",
    "Federacy",
    "Topcoder",

    # ===== Penetration Testing Tools =====
    "Metasploit",
    "Cobalt Strike",
    "Burp Suite",
    "OWASP ZAP",
    "Nmap",
    "Nessus",
    "Core Impact",
    "Canvas",
    "BeEF",
    "Armitage",
    "Acunetix",
    "Invicti",
    "Qualys WAS",
    "Pentest-Tools.com",
    "Intruder",
    "Immuniweb",
    "Probely",
    "Detectify",
    "StackHawk",
    "HCL AppScan",
    "NetSPI",
    "Rapid7 Metasploit",

    # ===== Network Monitoring =====
    "SolarWinds",
    "PRTG Network Monitor",
    "Paessler",
    "Nagios",
    "Zabbix",
    "Icinga",
    "Cacti",
    "LibreNMS",
    "Observium",
    "NetFlow Analyzer",
    "ManageEngine OpManager",
    "WhatsUp Gold",
    "Progress WhatsUp Gold",
    "Auvik",
    "LogicMonitor",
    "Kentik",
    "ThousandEyes",
    "AppNeta",
    "LiveAction",
    "Plixer Scrutinizer",
    "Flowmon",
    "ntopng",
    "Darkstat",
    "Pandora FMS",
    "Checkmk",
    "Datadog NPM",
    "Elastic Network",
    "Zeek",
    "Suricata",
    "Snort",
    "Bro IDS",
    "Moloch",
    "Arkime",
    "PacketBeat",

    # ===== Encryption / Key Management =====
    "DigiCert",
    "Entrust",
    "GlobalSign",
    "Sectigo",
    "Comodo CA",
    "Keyfactor",
    "Venafi",
    "AppViewX",
    "Smallstep",
    "Let's Encrypt",
    "PrimeKey",
    "SSL.com",
    "GoDaddy SSL",
    "Thales CipherTrust",
    "Voltage SecureData",
    "Micro Focus Voltage",
    "Protegrity",
    "Baffle",
    "Virtru",
    "PreVeil",
    "Boxcryptor",
    "Tresorit",
    "SpiderOak",
    "Vera",
    "Ionic Security",
    "Futurex",
    "Utimaco",
    "Thales Luna",
    "Fortanix",
    "Equinix SmartKey",
    "AWS KMS",
    "Azure Key Vault",
    "Google Cloud KMS",
    "HashiCorp Vault",

    # ===== Digital Forensics =====
    "Magnet Forensics",
    "OpenText EnCase",
    "Cellebrite",
    "Oxygen Forensics",
    "Exterro",
    "AccessData",
    "Paraben",
    "Belkasoft",
    "Binalyze",
    "Cado Security",
    "MSAB",
    "Grayshift",
    "Elcomsoft",
    "Passware",
    "X-Ways",
    "Autopsy",
    "Sleuth Kit",
    "Volatility Foundation",
    "Arsenal Recon",
    "SANS SIFT",
    "REMnux",
    "CAINE",
    "Paladin Forensics",
    "Sumuri",
    "Detego",
    "Nuix",
    "Relativity",
    "Everlaw",
    "Logikcull",
    "Disco",

    # ===== Cyber Range / Training =====
    "Hack The Box",
    "TryHackMe",
    "SANS",
    "Offensive Security",
    "OffSec",
    "INE",
    "Cybrary",
    "Immersive Labs",
    "RangeForce",
    "SimSpace",
    "Cyberbit",
    "AttackIQ Academy",
    "PentesterLab",
    "PortSwigger Web Security Academy",
    "Cybersecurity Lab",
    "PicoCTF",
    "CTFd",
    "HackTheBox Academy",
    "eLearnSecurity",
    "EC-Council",
    "CompTIA",
    "ISC2",
    "(ISC)2",
    "ISACA",
    "CREST",
    "GIAC",
    "Mile2",
    "CertNexus",
    "Infosec Institute",
    "Pluralsight",
    "Coursera",
    "Udemy",
    "A Cloud Guru",
    "Cloud Academy",

    # ===== Data Backup / DR =====
    "Veeam",
    "Rubrik",
    "Cohesity",
    "Commvault",
    "Veritas",
    "Druva",
    "Acronis",
    "Datto",
    "Arcserve",
    "Unitrends",
    "Axcient",
    "Carbonite",
    "Nakivo",
    "Zerto",
    "HYCU",
    "Keepit",
    "OwnBackup",
    "Spanning",
    "Backblaze",
    "Wasabi",
    "Cloudberry",
    "MSP360",

    # ===== Secure File Sharing =====
    "Kiteworks",
    "Accellion",
    "Axway",
    "MOVEit",
    "Progress MOVEit",
    "GoAnywhere",
    "Fortra GoAnywhere",
    "GlobalSCAPE",
    "Ipswitch",
    "Citrix ShareFile",
    "Egnyte",
    "Box",
    "Dropbox Business",
    "Google Drive",
    "OneDrive",
    "SharePoint",
    "Tresorit",
    "SpiderOak",
    "Sync.com",
    "pCloud",
    "Internxt",
    "Nextcloud",
    "ownCloud",
    "Seafile",
    "FileSender",

    # ===== IoT Security =====
    "Armis",
    "Forescout",
    "Claroty",
    "Nozomi Networks",
    "Dragos",
    "TXOne Networks",
    "SCADAfence",
    "Otorio",
    "Radiflow",
    "Waterfall Security",
    "Verve Industrial",
    "Bayshore Networks",
    "Fortinet OT",
    "Honeywell Forge",
    "Schneider Electric",
    "Siemens",
    "ABB",
    "Rockwell Automation",
    "Cisco IoT Security",
    "Microsoft Defender for IoT",
    "AWS IoT Device Defender",
    "Palo Alto IoT Security",
    "Medigate",
    "CyberMDX",
    "Asimily",
    "Ordr",
    "Phosphorus",
    "Finite State",
    "Vdoo",
    "BugProve",
    "Onekey",
    "Sternum",
    "Karamba Security",
    "C2A Security",
    "Argus Cyber Security",
    "PlaxidityX",
    "Upstream Security",

    # ===== Data Classification / DLP (Extended) =====
    "Titus",
    "Boldon James",
    "Janusnet",
    "Getvisibility",
    "Congruity360",
    "Spirion",
    "Varonis",
    "Netwrix",
    "Safetica",
    "CoSoSys",
    "Digital Guardian",
    "Code42",
    "Teramind",
    "Nightfall AI",
    "Polymer DLP",
    "Metomic",
    "Cyberhaven",
    "Microsoft Purview",
    "Symantec DLP",
    "Forcepoint DLP",
    "McAfee DLP",
    "Trellix DLP",
    "Proofpoint DLP",
    "Netskope DLP",
    "Zscaler DLP",
    "GTB Technologies",
    "Fidelis Network",
    "Clearswift",
    "Zecurion",

    # ===== SASE / SSE Vendors =====
    "Zscaler",
    "Netskope",
    "Palo Alto Prisma Access",
    "Cato Networks",
    "Cloudflare One",
    "Cisco Umbrella",
    "Forcepoint ONE",
    "Skyhigh Security",
    "Lookout",
    "iboss",
    "Versa Networks",
    "VMware SASE",
    "Fortinet FortiSASE",
    "Barracuda SecureEdge",
    "Open Systems",
    "Aryaka",
    "Citrix",

    # ===== Additional Companies from Various Sources =====
    "Abnormal Security",
    "Absolute Software",
    "Abstract Security",
    "Acalvio",
    "Accurics",
    "Action1",
    "Adlumin",
    "Agari",
    "Akamai",
    "Alkira",
    "Anchore",
    "Apex Technology Services",
    "Appgate",
    "Arista Networks",
    "Aruba Networks",
    "Automox",
    "Aviatrix",
    "Axis Security",
    "BackBox",
    "Backslash Security",
    "Banyan Security",
    "BitSight",
    "Blackpoint Cyber",
    "BlueCat",
    "Brinqa",
    "Cado Security",
    "Cavelo",
    "CertiK",
    "Cisco Duo",
    "Cisco ISE",
    "Cloudflare Access",
    "CloudPassage",
    "Coalfire",
    "Code42",
    "ColorTokens",
    "ConductorOne",
    "Constella Intelligence",
    "Cribl",
    "CrowdSec",
    "CyberInt",
    "Cybersixgill",
    "CyCognito",
    "Dasera",
    "Dataprise",
    "Deepwatch",
    "Delinea",
    "DetectID",
    "Dome9",
    "Duo Security",
    "Eclypsium",
    "Elisity",
    "Ermetic",
    "Eureka Security",
    "Evervault",
    "ExtraHop",
    "Feitian",
    "Fingerprint",
    "FireEye",
    "FireMon",
    "Garland Technology",
    "Gigamon",
    "GoSecure",
    "GoodAccess",
    "Guardicore",
    "Halcyon",
    "HarfangLab",
    "Hexagate",
    "Hillstone Networks",
    "IONIX",
    "Kasada",
    "Keeper",
    "KELA",
    "Kudelski Security",
    "Lacework",
    "LayerX",
    "LevelBlue",
    "Lightspin",
    "Lumu Technologies",
    "Mammoth Cyber",
    "ManageEngine",
    "MaterialSecurity",
    "Menlo Security",
    "Mimecast",
    "Minerva Labs",
    "MISP",
    "Mitiga",
    "Mocana",
    "Morphisec",
    "Netography",
    "Netskope",
    "Netsurion",
    "Nightfall AI",
    "Noname Security",
    "Normalyze",
    "Nozomi Networks",
    "Nucleus Security",
    "NuHarbor Security",
    "Nuspire",
    "Obsidian Security",
    "Onekey",
    "OpenText",
    "OPSWAT",
    "PacketViper",
    "Panorays",
    "Pentera",
    "Perception Point",
    "PerimeterX",
    "Permiso",
    "Phosphorus",
    "Picus Security",
    "PlexTrac",
    "Plurilock",
    "Portnox",
    "Push Security",
    "Reco",
    "Red Access",
    "RevealSecurity",
    "Ridge Security",
    "Rubrik",
    "Runzero",
    "SafeBase",
    "SASE Secure",
    "SCADAfence",
    "Scribe Security",
    "SecurityBridge",
    "Sekoia",
    "Senhasegura",
    "Sentra",
    "Sevco Security",
    "Silverfort",
    "Skybox Security",
    "Socket",
    "Sonrai Security",
    "SpinOne",
    "Stamus Networks",
    "Stream Security",
    "StrikeReady",
    "SURF Security",
    "Suridata",
    "Sweet Security",
    "Sygnia",
    "Symmetry Systems",
    "Team Cymru",
    "Tehtris",
    "ThreatBook",
    "ThreatModeler",
    "ThreatX",
    "Todyl",
    "TrapX",
    "Trellix",
    "Trulioo",
    "TrustCloud",
    "Upwind",
    "Valence Security",
    "Veriti",
    "Vicarius",
    "Viavi Solutions",
    "Votiro",
    "Wallarm",
    "Whistic",
    "Wing Security",
    "Zenity",
    "Zero Networks",
    "ZeroFox",

    # ===== Additional Security Companies =====
    "Acunetix",
    "Alert Logic",
    "Appdome",
    "Arctic Wolf",
    "Argus Cyber Security",
    "Arista",
    "Barracuda Networks",
    "Bitglass",
    "BlackBerry Cylance",
    "Blumira",
    "Booz Allen",
    "CardinalOps",
    "Centrify",
    "Check Point Software",
    "Chronicle",
    "Cisco Meraki",
    "Cisco Secure",
    "CIS",
    "Comodo",
    "ConnectWise",
    "CrowdStrike Falcon",
    "Cybereason",
    "CyberGRX",
    "DarkReading",
    "DefectDojo",
    "Dell SecureWorks",
    "Duo",
    "EY Cybersecurity",
    "F5 Networks",
    "FireEye Mandiant",
    "Forcepoint",
    "Fortinet FortiGate",
    "FoxGuard",
    "Graylog",
    "Greenbone",
    "Group-IB",
    "Guardicore Centra",
    "HCL",
    "Honeywell",
    "IBM QRadar",
    "Illumio",
    "Infosec",
    "Intel Security",
    "Juniper",
    "Kaseya",
    "Mandiant",
    "ManTech",
    "McAfee Enterprise",
    "MicroStrategy",
    "N-able",
    "NetScout",
    "Netwrix",
    "Nexpose",
    "NinjaOne",
    "NIST",
    "Okta",
    "OpenText",
    "Optiv Security",
    "Parsons",
    "Plixer",
    "Positive Technologies",
    "Prevalent",
    "ProcessUnity",
    "PwC",
    "Recorded Future",
    "Resolver",
    "Riskonnect",
    "SafeNet",
    "SAIC",
    "SailPoint",
    "Samsung Knox",
    "SAP Security",
    "Schneider Electric Cybersecurity",
    "SentinelOne Singularity",
    "SimpliSafe",
    "Skybox",
    "SonicWall",
    "Sophos Central",
    "SpecterOps",
    "Stormshield",
    "Swimlane",
    "Symantec",
    "Tanium",
    "TechTarget",
    "Tenable.io",
    "Thales Group",
    "ThreatConnect",
    "Tufin",
    "Trustwave SpiderLabs",
    "Unisys Stealth",
    "UpGuard",
    "Vectra AI",
    "Venafi",
    "Verint",
    "VMware",
    "WatchGuard Technologies",
    "WithSecure",
    "Xerox Security",
    "ZeroFox",

    # ===== Open Source Security Projects =====
    "OSSEC",
    "Wazuh",
    "Snort",
    "Suricata",
    "Zeek",
    "pfSense",
    "OPNsense",
    "Untangle",
    "IPFire",
    "Smoothwall",
    "ClearOS",
    "Endian",
    "Sophos UTM Home",
    "Security Onion",
    "SELKS",
    "AlienVault OSSIM",
    "Graylog",
    "Wazuh",
    "ELK Stack",
    "OpenSearch",
    "Grafana",
    "MISP",
    "OpenCTI",
    "IntelMQ",
    "Hail Mary",
    "GRR Rapid Response",
    "Velociraptor",
    "osquery",
    "Kolide",
    "Fleet",
    "Santa",
    "Cuckoo Sandbox",
    "ANY.RUN",
    "Joe Sandbox",
    "Hybrid Analysis",
    "VirusTotal",
    "MalwareBazaar",
    "URLhaus",
    "PhishTank",
    "AbuseIPDB",
    "Spamhaus",
    "DNSBL",
    "Shodan",
    "Censys",
    "ZoomEye",
    "Fofa",
    "Hunter.io",
    "SecurityTrails",
    "BuiltWith",
    "Wappalyzer",
    "Retire.js",
    "is-website-vulnerable",

    # ===== Additional from memory — deep list =====
    # Network equipment vendors with security
    "Aruba",
    "HPE",
    "Hewlett Packard Enterprise",
    "Ruckus",
    "Ubiquiti",
    "Cambium Networks",
    "Extreme Networks",
    "Netgear",
    "TP-Link",
    "D-Link",
    "MikroTik",
    "Meraki",
    "Mist Systems",
    "Arista Networks",

    # Telecom security
    "Nokia",
    "Ericsson",
    "Huawei",
    "Samsung Networks",
    "Mavenir",
    "Affirmed Networks",
    "Netcracker",
    "MATRIXX Software",
    "Celona",
    "Betacom",
    "Cradlepoint",

    # Privacy tech
    "Privado",
    "Transcend",
    "Ethyca",
    "Mine",
    "Skyflow",
    "Evervault",
    "Cape Privacy",
    "Duality Technologies",
    "Enveil",
    "Inpher",
    "Opaque Systems",
    "Baffle",
    "IronCore Labs",
    "Virtru",
    "PreVeil",
    "Vera",
    "Ionic Security",

    # Security consulting firms
    "Mandiant",
    "CrowdStrike Services",
    "Secureworks",
    "NCC Group",
    "WithSecure Consulting",
    "Trustwave SpiderLabs",
    "Bishop Fox",
    "Cobalt Labs",
    "NetSPI",
    "Praetorian",
    "Rapid7 Services",
    "FireEye Services",
    "Optiv",
    "Protiviti",
    "Kroll",
    "Stroz Friedberg",
    "Control Risks",
    "FTI Consulting",
    "Alvarez & Marsal",
    "Navigant",
    "PwC Cybersecurity",
    "Deloitte Cyber",
    "EY Cybersecurity",
    "KPMG Cyber",
    "Accenture Security",
    "IBM X-Force",
    "AT&T Alien Labs",
    "Lumen Black Lotus Labs",
    "Cisco Talos",
    "Palo Alto Unit 42",
    "Trend Micro Research",
    "ESET Research",
    "Kaspersky GReAT",
    "Bitdefender Labs",
    "Sophos X-Ops",
    "SentinelLabs",
    "Microsoft MSRC",
    "Google Project Zero",
    "Google TAG",
    "Meta Security",
    "Apple Security",
    "Amazon Security",

    # Government / Standards bodies with tools
    "CISA",
    "NIST",
    "NSA",
    "NCSC",
    "ENISA",
    "BSI",
    "ANSSI",
    "AIVD",
    "ASD",
    "CCCS",
    "CERT-CC",
    "US-CERT",
    "FIRST",
    "MITRE",
    "CIS",
    "DISA",
    "NIST CSF",
    "ISO 27001",

    # Insider threat / DLP extended
    "Teramind",
    "Veriato",
    "ObserveIT",
    "Dtex Systems",
    "Code42 Incydr",
    "Cyberhaven",
    "Proofpoint ITM",
    "Gurucul",
    "Securonix UEBA",
    "Exabeam",
    "Microsoft Purview Insider Risk",
    "DTEX InTERCEPT",

    # More from Cybersecurity 500 and market maps
    "Absolute Software",
    "Agari",
    "Agiliance",
    "Alertus Technologies",
    "AlgoSec",
    "Allure Security",
    "Anomalix",
    "Aperio Systems",
    "Apricorn",
    "Armo",
    "Assured Enterprises",
    "Atacama",
    "Attila Security",
    "Avocado Systems",
    "Awake Security",
    "Axellio",
    "Axiad",
    "Bandura Cyber",
    "BastionZero",
    "Bay Dynamics",
    "Bayshore Networks",
    "Bcyber",
    "Bedrock Security",
    "Bitahoy",
    "BlackCloak",
    "BluBracket",
    "BlueFort Security",
    "BluVector",
    "BOD Security",
    "Bsquare",
    "C1 Security",
    "Calyptix",
    "CaptureRx",
    "Cavirin",
    "Certes Networks",
    "ChainGuard",
    "Chariot Solutions",
    "CipherCloud",
    "CircleCI",
    "Clarified Security",
    "Cleafy",
    "CloudVector",
    "Coda Intelligence",
    "Cognni",
    "Commvault",
    "Concentric AI",
    "ControlPlane",
    "Coralogix",
    "Corsa Security",
    "Cranium",
    "Craw Security",
    "CUJO AI",
    "CybelAngel",
    "Cyber Observer",
    "CyberArk Labs",
    "CyberDrain",
    "CyberFortress",
    "CyberMaxx",
    "CyberOwl",
    "CyberQ Group",
    "CyberReady",
    "CyberX (Microsoft)",
    "CyFirma",
    "Cymptom",
    "Cynalytica",
    "Cynch Security",
    "Cynergy",
    "CyOps",
    "Cyren",
    "Cysurance",
    "Cytidel",
    "Dataminr",
    "Deduce",
    "Deepfactor",
    "DefenseStorm",
    "Devo Technology",
    "Diode",
    "Dispersive Networks",
    "DivvyCloud",
    "DoControl",
    "Drift Security",
    "Dtex",
    "Duo Security (Cisco)",
    "Eclipsium",
    "Eden Data",
    "EiQ Networks",
    "Elpha Secure",
    "Endace",
    "Ensilo",
    "Entro Security",
    "Epiq",
    "Ethyca",
    "EvolutionQ",
    "Expanse",
    "ExtraHop Networks",
    "Featurespace",
    "Fenror7",
    "Fidelis Cybersecurity",
    "FileFlex",
    "Fireblocks",
    "FirstPoint Mobile Guard",
    "FluentBit",
    "Forcepoint",
    "ForgeRock",
    "Fortanix",
    "Fraud.net",
    "FullArmor",
    "Galvanize",
    "Gem Security",
    "Glasswall",
    "Grapl",
    "Grip Security",
    "Guardio",
    "Gurucul",
    "HacWare",
    "Halborn",
    "Harbor Networks",
    "Heliax",
    "Hillstone",
    "Hub Security",
    "Hypr",
    "Immuta",
    "Imperva",
    "Indegy",
    "Infocyte",
    "InfraGard",
    "Interos",
    "Intrusion",
    "IronNet Cybersecurity",
    "IronScales",
    "Ivanti",
    "JFrog",
    "Keysight",
    "Keytos",
    "Kiteworks",
    "Kobalt",
    "Konfidas",
    "Kontrol",
    "Krypt",
    "Lastline",
    "Lightspin",
    "Limacharlie",
    "Locate2u",
    "LogicHub",
    "LogPoint",
    "Logsign",
    "Lumu",
    "Lupin & Holmes",
    "MagicCube",
    "Managed Methods",
    "Metomic",
    "MixMode",
    "Mocana",
    "Morpheus Data",
    "Morphisec",
    "Motiv ICT Security",
    "Moxfive",
    "NetEnrich",
    "Netography",
    "NetWitness",
    "Nile",
    "Nortonlifelock",
    "NovaTech",
    "NuData Security",
    "Nuvolo",
    "Nvisium",
    "OctoAI",
    "Okera",
    "Oleria",
    "OneSpan",
    "Oort",
    "Operant AI",
    "Orchestra Group",
    "Ordr",
    "Outflank",
    "OwnCloud",
    "OwnSecurity",
    "Paladin Cloud",
    "Panorama9",
    "Papaya Global",
    "Perch Security",
    "Phylum",
    "Piiano",
    "Plextrac",
    "Polyverse",
    "Postman",
    "Qualys",
    "Quantum Xchange",
    "QuintessenceLabs",
    "Qwiet",
    "Ramp",
    "RangeForce",
    "Rank Software",
    "Recorded Future",
    "Red Sift",
    "RedSeal",
    "Reinforced AI",
    "Reliaquest",
    "Remediant",
    "Rezonate",
    "RiskOptics",
    "Rumble",
    "Rumble Network Discovery",
    "SafeGuard Cyber",
    "Saviynt",
    "Scalarr",
    "Scribe Security",
    "SecureAuth",
    "SecurEnvoy",
    "SecurityBridge",
    "SecurityHQ",
    "Segasec",
    "Semperis",
    "SentinelOne",
    "Sera-Brynn",
    "Sevco",
    "ShiftLeft",
    "Siemba",
    "SimSpace",
    "SixMap",
    "Skyhawk Security",
    "SlashNext",
    "Snapattack",
    "Snowbit",
    "Sonatype",
    "Spec",
    "SpearTip",
    "SpecterOps",
    "Spin Technology",
    "Stairwell",
    "StellarCyber",
    "StepSecurity",
    "StoneFly",
    "Sumo Logic",
    "SURF",
    "Sysdig",
    "Tanium",
    "TeamViewer",
    "Tenable",
    "Tessian",
    "ThreatMark",
    "ThreatQuotient",
    "ThreatSpike",
    "ThreatWarrior",
    "Todyl",
    "TokenEx",
    "Torq",
    "Traced",
    "TraceSecurity",
    "Trelix",
    "Trellix",
    "Trustar",
    "TrustArc",
    "TrustWave",
    "TXOne",
    "Uniken",
    "Uptycs",
    "Utimaco",
    "V2 Systems",
    "Varonis",
    "Verizon",
    "Verodin",
    "Virsec",
    "VulnCheck",
    "Vultr",
    "WatchTowr",
    "Wazuh",
    "Webroot",
    "WiCyS",
    "Wing Security",
    "XDR",
    "Xlabs Security",
    "YL Ventures",
    "Zerofox",
    "Zimperium",
    "Zippia",
    "Zoho",
    "Zorus",

    # ===== More emerging / niche companies =====
    "Abnormal Security",
    "Abstract Security",
    "Acalvio Technologies",
    "Adallom",
    "Aembit",
    "Agile Defense",
    "AirEye",
    "Aitheon",
    "AKA Identity",
    "Align Cybersecurity",
    "Allot",
    "Altair Engineering",
    "Ambient.ai",
    "Anitian",
    "Anomali ThreatStream",
    "AntiFragile Systems",
    "Aperture Data",
    "Appsian",
    "Aquia",
    "Aravo",
    "Area 1",
    "Armata Cyber Security",
    "Assetnote",
    "Astrix Security",
    "AtomicJar",
    "Authentic8 Silo",
    "Avanade",
    "Axoniize",
    "BastionZero",
    "Bedrock Security",
    "Bitahoy",
    "BlackCloak",
    "Blaze Information Security",
    "Blocky",
    "BoldCloud",
    "Breachlock",
    "Bridewell Consulting",
    "BuddoBot",
    "Build38",
    "Buoyant",
    "ByteDance Security",
    "C3M",
    "CalypsoAI",
    "Canonic Security",
    "Capsule8",
    "Carbide",
    "Cerby",
    "Cipher",
    "Circa",
    "Citadel",
    "ClearData",
    "ClearNetwork",
    "Climax Technology",
    "CloudDefense.AI",
    "CloudVector",
    "Cobalt.io",
    "Cofense PhishMe",
    "ComplianceForge",
    "ContraForce",
    "Corsha",
    "Cossack Labs",
    "Crossbow Labs",
    "Crypsis Group",
    "CryptoMove",
    "Curios",
    "Cyber Crucible",
    "Cyber Tec Security",
    "CyberArrow",
    "CyberCX",
    "CyberEdge Group",
    "CyberGRX",
    "CyberHoot",
    "CyberMDX",
    "CyberNB",
    "CyberOK",
    "CyberPeace Foundation",
    "CyberPoint",
    "CyberSmart",
    "CybrScore",
    "Cydarm",
    "Cyphercor",
    "DarkOwl",
    "DarkScope",
    "DarkTrace",
    "DataSunrise",
    "DataVisor",
    "DeepSurface Security",
    "Delta Risk",
    "Descope",
    "DevOcean",
    "DigiCert",
    "DivvyCloud",
    "Dragnet Surveillance",
    "DXC Technology",
    "EdgeBit",
    "Edgewise Networks",
    "Elastio",
    "ElevenPaths",
    "Elliptic",
    "Ember",
    "Empow Cyber Security",
    "EndpointArmor",
    "Endure Secure",
    "Ensighten",
    "Enzoic",
    "Esentire",
    "Everly Health",
    "F5 Shape",
    "Faraday",
    "FedRAMP",
    "Fidelis",
    "FileCloud",
    "Forescout",
    "Fortify Software",
    "FortMesa",
    "Fugue",
    "Galvanick",
    "GBProtect",
    "Gems",
    "Gradient Cyber",
    "Gray Analytics",
    "GreatHorn",
    "GuardiCore",
    "Guardknox",
    "Hackuity",
    "HealthcareInfoSecurity",
    "HelpAG",
    "HelpSystems",
    "Fortra",
    "HighGround",
    "Horangi",
    "Hub City Media",
    "Hunton Andrews Kurth",
    "ICS-CERT",
    "IDShield",
    "ImpactCyber",
    "Incedo",
    "IncidentResponse.com",
    "InfiniDome",
    "InformaCast",
    "Ingalls Information Security",
    "Innofactor",
    "InQuest",
    "Insider Threat Management",
    "InterVision",
    "ISEC7",
    "Ixia",
    "Jamcracker",
    "K2 Cyber Security",
    "KingsGuard",
    "Knowmadics",
    "L7 Defense",
    "Lacoon Mobile Security",
    "Lasso",
    "Launchpad Security",
    "Lineaje",
    "LogMeIn",
    "Lookout Mobile",
    "Maldaptive",
    "ManagedMethods",
    "MazeBolt",
    "MITRE Engenuity",
    "Mobalytics",
    "MobileSOC",
    "Molerats",
    "Monokee",
    "MorganFranklin",
    "Morphus",
    "MWR InfoSecurity",
    "Netacea",
    "NetFort",
    "Netography",
    "NetRise",
    "NetworkSec",
    "Niara",
    "Nisos",
    "NotPetya",
    "NS8",
    "Nyotron",
    "Oasis",
    "ObjectSecurity",
    "OnDefend",
    "OneLogin",
    "OnGarde",
    "Open Raven",
    "OpenDNS",
    "OpenID",
    "Opinnate",
    "OpSec Security",
    "Orca Security",
    "OTORIO",
    "Outseer",
    "OwnCloud",
    "OxSecurity",
    "PacketFabric",
    "PCYSYS",
    "PeerSpot",
    "Penfield.AI",
    "Pensar",
    "Perforce",
    "PerimeterX",
    "Phosphorus Cybersecurity",
    "Phylum",
    "Pistachio",
    "PlainID",
    "Polar Security",
    "Polaris Infosec",
    "Positive Technologies",
    "Preempt Security",
    "ProcessBolt",
    "Proficio",
    "Protectimus",
    "Proton AG",
    "ProtonMail",
    "Protonmail",
    "QomplX",
    "Qualitia",
    "Quantum Knight",
    "QWERX",
    "RAD Security",
    "RankedRight",
    "Rapid7 Labs",
    "RapidFire Tools",
    "Rapid7 velociraptor",
    "Reachability",
    "ReadyCloud",
    "RealVNC",
    "Redacted",
    "Redis",
    "Reflectiz",
    "ResiliAnt",
    "Revelstoke",
    "Rezonate",
    "RiskIQ",
    "Roboto Systems",
    "Rollbar",
    "Root9B",
    "RunSafe Security",
    "S21sec",
    "SafeBreach",
    "SafeNet",
    "Safewalk",
    "Saltcorn",
    "Sandfly Security",
    "Savant",
    "Scantist",
    "SecBI",
    "Seceon",
    "SecLytics",
    "SecNeurex",
    "SecOps Group",
    "Sectigossl",
    "SecuLore Solutions",
    "SecureAge",
    "SecureBrain",
    "SecureIQLab",
    "SecureLink",
    "SecureMac",
    "SecureStack",
    "SecureVisio",
    "SecuTech Solutions",
    "Segasec",
    "Sego",
    "SekurSafe",
    "SemperSecure",
    "Sepio",
    "SetSail",
    "Sevco",
    "Shorepoint",
    "Silobreaker",
    "SilverSky",
    "SiO4",
    "Siren Forensics",
    "SiteLock",
    "Sixgill",
    "Sliide",
    "SlowMist",
    "Smokescreen Technologies",
    "SnapAttack",
    "Solana Security",
    "Sotero",
    "Sourcefire",
    "SparkCognition",
    "Spec",
    "SpiderSilk",
    "Spirent",
    "Spyderbat",
    "StackAware",
    "Stairwell",
    "Stellar Cyber",
    "StepSecurity",
    "StoneFly",
    "StrikeReady",
    "Strongarm",
    "Styra",
    "SubmitForce",
    "Sumsub",
    "SynerComm",
    "TechR2",
    "Tempered Networks",
    "Tenzir",
    "ThirdPartyTrust",
    "ThreatGEN",
    "ThreatStop",
    "ThreatWarrior",
    "Titaniam",
    "TorGuard",
    "Torsion Information Security",
    "Trustifi",
    "Trustwave",
    "Tychon",
    "UKCloud",
    "UncommonX",
    "Unisys",
    "Untangle NG",
    "Uptycs",
    "V-Key",
    "Valiant TMS",
    "Valtix",
    "Variti",
    "VectorShield",
    "Venation",
    "Vera Security",
    "VeraCrypt",
    "Vercara",
    "Verified",
    "Verodin",
    "Versa Networks",
    "Vinculum Group",
    "Vipre Security",
    "VirSecure",
    "Virsec Systems",
    "Virsec",
    "VisibleRisk",
    "VPNFilter",
    "VulnCheck",
    "Warden",
    "WatchTowr",
    "Whitebox Security",
    "WitFoo",
    "XDR",
    "Xperi",
    "Xtreme Security",
    "Yext",
    "YL Ventures",
    "Zafran",
    "ZecOps",
    "Zenoss",
    "ZeroHack",
    "Zilla Security",
    "Zimperium",
    "Zorus",
    "Zyxel",
    # ===== Additional batch to reach 5000+ =====
    # More RSAC / Black Hat exhibitors
    "Abnormal Platform",
    "Acalvio Shadow Plex",
    "Acemlabs",
    "ACI Learning",
    "Acreto",
    "ActiveCyber",
    "ActiveFence",
    "AdaptiveMobile Security",
    "Adlumin Platform",
    "AET Europe",
    "AgileBlue SOC",
    "AgileSec",
    "Aiden Technologies",
    "AirEye",
    "Airgap Networks",
    "AirgapFlowFence",
    "AKA Identity",
    "Akto",
    "Alertus Technologies",
    "Algosec Firewall Analyzer",
    "AlgoSec",
    "Alibaba Cloud Security",
    "Align Cybersecurity",
    "Allgress",
    "Allure Security Technology",
    "Altitude Networks",
    "Amberflo",
    "Ambient.ai",
    "Anetac",
    "Angoka",
    "Anitian",
    "AntiFragile Systems",
    "Anvil Secure",
    "AnyVision",
    "Apex Technology",
    "Apicurio",
    "Aplite",
    "AppCheck",
    "AppDome Mobile",
    "Appknox",
    "Appricorn",
    "AppSec Phoenix",
    "AppSolid",
    "AppTrana",
    "Apricorn",
    "Aqua DTA",
    "Aqua vShield",
    "Aravo",
    "Arbor Networks",
    "Archon Secure",
    "Arcturus",
    "Ardent Privacy",
    "ArmorCode",
    "ArmorText",
    "Ascend Technologies",
    "Aserto",
    "ASG Technologies",
    "ASPIA InfoTech",
    "AsTech",
    "Atakama",
    "Atos BullSequana",
    "AttackFlow",
    "Attestiv",
    "Aurora Systems",
    "AuthN by IDEE",
    "AutoRABIT Security",
    "Ava Security",
    "Avalor",
    "Avanade",
    "Avetta",
    "Aviatrix Security",
    "BalkanID",
    "Bandura Cyber",
    "Banshee",
    "Barracuda MSP",
    "Basis Technology",
    "Bastille Networks",
    "BforeAI",
    "BG Networks",
    "BigPanda AIOps",
    "Binary Defense Platform",
    "Binarly Platform",
    "BioConnect",
    "BioSig Technologies",
    "BitDam",
    "Bitahoy",
    "Bitninja Server",
    "BlackBerry AtHoc",
    "BlackBerry QNX",
    "BlackBerry UEM",
    "Blackbird AI",
    "BlackCloak",
    "Blackwell Security",
    "Blancco",
    "Blaze Information Security",
    "Blocky",
    "Blue Cedar",
    "Blue Coat",
    "Blue Hexagon",
    "Blue Lava",
    "Blue Mantis",
    "Blue Ridge Networks",
    "Blue Team Alpha",
    "Blue Voyant MDR",
    "Blueshift Cybersecurity",
    "Bluink",
    "BMC Helix",
    "Boole Server",
    "BoostSecurity",
    "Bridewell",
    "Bromium",
    "BTB Security",
    "BugProve",
    "BugSec",
    "Build38",
    "BullWall",
    "Buoyant",
    "C1 Risk",
    "C3M",
    "CACI Cyber",
    "Calian Cyber",
    "Callsign Platform",
    "Calyptix Security",
    "CaptureRx",
    "Carbide",
    "Carceron",
    "Caveonix",
    "CCM Security",
    "Censinet",
    "CentricMinds",
    "Cerberus Sentinel",
    "Cerby Identity",
    "Certo Security",
    "Chalk Mountain",
    "Chariot Solutions",
    "CheckRed",
    "Chimera Security",
    "Cigent Technology",
    "CipherCloud",
    "CipherTrust",
    "Circa",
    "Cisco Kenna Security",
    "Cisco SecureX",
    "Cisco Stealthwatch",
    "Cisco Tetration",
    "Cisco ThousandEyes",
    "Citadel Information Group",
    "CivicPlus",
    "ClarifiedSecurity",
    "ClearDATA",
    "ClearNetwork",
    "ClearVector",
    "Climax Technology",
    "CloudDefense.AI",
    "CloudKnox",
    "CloudMask",
    "CloudSEK",
    "CloudSOC",
    "ClouDNS",
    "Clumio",
    "CoalFire Labs",
    "CODA Intelligence",
    "Code Intelligence",
    "Codelock",
    "Codenotary",
    "Cognni",
    "Cognito AI",
    "Colt Cyber",
    "Comcast Business SecurityEdge",
    "Command Zero",
    "ComplyCloud",
    "Comtech Cybersecurity",
    "Concentric AI",
    "ConfigOS",
    "Confluera",
    "Copado Security",
    "Coralogix Security",
    "Cork Protection",
    "Corellium",
    "CortexPrime",
    "CoverMyMeds Security",
    "Craw Security India",
    "CrossPoint Capital",
    "CrowdStrike Humio",
    "Crypteron",
    "CryptoStopper",
    "CUJO AI",
    "Cure53",
    "Curtail Security",
    "Curtiss-Wright Defense",
    "CybelAngel Platform",
    "Cyber Observer",
    "CyberArk Conjur Cloud",
    "CyberArk Identity Platform",
    "CyberArk Workforce Identity",
    "CyberCatch",
    "CyberDrain",
    "CyberFOX",
    "CyberHat",
    "CyberKnight Technologies",
    "CyberPion",
    "CyberRes",
    "CyberVadis",
    "CybrHawk",
    "CyCraft",
    "CyFIR",
    "CyGlass",
    "CyNtec",
    "Cypago",
    "Cyrebro",
    "CyScope",
    "Cytidel",
    "Dasgate",
    "DataFleets",
    "DataKitchen",
    "DataLocker",
    "DataSunrise",
    "DataTribe",
    "DatAnswers",
    "Debricka",
    "Deepcode AI",
    "DeepInfo",
    "DeepSurface Security",
    "DeepWatch MDR",
    "DefendEdge",
    "DefenseStorm",
    "Delinea DevOps Secrets",
    "Delinea Server Suite",
    "Detexian",
    "DevOcean Security",
    "Device Authority",
    "DeviceTotal",
    "Devo SIEM",
    "Devo Technology",
    "DigiSec360",
    "DigitalStakeout",
    "Diode",
    "Discern Security",
    "Dispersive Networks",
    "DisruptOps",
    "DivvyCloud Platform",
    "DNStwist",
    "DoubleVerify",
    "Dovecot",
    "Drawbridge",
    "Drift Security",
    "Druva Phoenix",
    "Druva inSync",
    "DuoKey",
    "Dusk Network",
    "DXC Cyber",
    "Dynatrace Application Security",
    "E8 Security",
    "EagleView Security",
    "Ebryx",
    "EdgeBit",
    "Edgewise Networks",
    "EiQ Networks Platform",
    "Elastio",
    "ElevenPaths",
    "EliteSec",
    "Elpha Secure",
    "Embodied Intelligence",
    "Emsisoft Business Security",
    "Endace",
    "Endgame",
    "Endor Labs Security",
    "Ensighten",
    "Ensilo",
    "Enterprise Immune System",
    "Entro Security",
    "Enzoic",
    "Eperi",
    "Epiq Global",
    "Ermetic CIEM Platform",
    "Ethyca Fides",
    "Eurotech",
    "EventTracker SIEM",
    "Eviden Cybersecurity",
    "Evident Security Platform",
    "EvolutionQ",
    "ExcelForce",
    "Exein IoT",
    "Exium",
    "Expanse (Palo Alto)",
    "Extenua",
    "F5 Distributed Cloud",
    "Falcon LogScale",
    "FalconStor",
    "Farsight Security DNSDB",
    "Feroot Security",
    "Fenror7",
    "Fidelis Cybersecurity Platform",
    "FieldEffect Covalence",
    "FileFlex",
    "FileCloud Security",
    "Finsec Innovation Lab",
    "FireCompass",
    "FireLayers",
    "FirstPoint Mobile Guard",
    "Fishtech Group",
    "Fixify",
    "Flare Systems",
    "Fletch AI",
    "Fognigma",
    "Forcepoint CASB",
    "ForceShield",
    "Foresiet",
    "Fortalice Solutions",
    "FortiProxy",
    "Fortscale",
    "FoxGuard Solutions",
    "FPT Security",
    "Fraud.net",
    "Frsecure",
    "FullArmor",
    "Fugue Cloud Security",
    "GajShield",
    "Galvanick",
    "Galvanize Platform",
    "Gamma Group",
    "GCA Automated IoT",
    "Gem Cloud Security",
    "Geobridge",
    "GetVisibility AI",
    "GlassWire",
    "Glasswall CDR",
    "GlobalPlatform",
    "GlowRoot",
    "GoSecure Titan",
    "Gray Analytics",
    "GreatHorn",
    "Green Hills Software",
    "Green Radar",
    "GroupSense",
    "Guardicore Centra",
    "Guardio Browser Security",
    "Guardium Insights",
    "Guardsquare",
    "GuidePoint Security",
    "Gutsy Platform",
    "HacWare",
    "Hadrian Security",
    "Harbor Networks",
    "Hawk AI",
    "Haystax Technology",
    "Heimdal Security",
    "Helidon Security",
    "HighSide",
    "Honeynet Project",
    "Horangi Warden",
    "Hub Security",
    "Hubble Technology",
    "HumanFirewall",
    "HyperGrid",
    "HyperVerge",
    "Hysolate",
    "Hypr Identity",
    "iC Consult",
    "ID.me",
    "Identiv",
    "IDmachines",
    "Igloo Security",
    "ImpactCyber",
    "Imperva Bot Management",
    "Incapsula",
    "Incedo Inc",
    "Infocyte Platform",
    "InformaCast",
    "Ingalls Cybersecurity",
    "Ingrian Networks",
    "Innofactor Security",
    "InQuest Labs",
    "Inspectiv",
    "IntegriCom",
    "Intelligent Waves",
    "Interos Supply Chain",
    "InterVision Systems",
    "Intrusion Inc",
    "IOActive Security",
    "IONIX ASM",
    "iProov",
    "IriusRisk Platform",
    "IronNet Cybersecurity",
    "ISEC7 Group",
    "iStorage",
    "Ivalua Security Procurement",
    "Ivanti Application Control",
    "Ixia (Keysight)",
    "Jask ASOC",
    "Javelin Networks",
    "JFrog Xray Security",
    "Jscrambler",
    "K2 Cyber Security",
    "Kameleon Security",
    "Karambit.AI",
    "Keeper Enterprise",
    "Keisuke Security",
    "KeyFactor Command",
    "Keysight Network Security",
    "Keytos",
    "KnectIQ",
    "Knowmadics",
    "Knownsec",
    "Kobalt.io",
    "Koide Technology",
    "Konfidas",
    "Kontrol Cyber",
    "Krypt AI",
    "KryptoKloud",
    "Kustodian",
    "KYND Risk",
    "L7 Defense",
    "Lacoon Mobile Security",
    "Lansweeper Security",
    "Lastline",
    "Launchpad Security",
    "Leviathan Security Group",
    "Limacharlie EDR",
    "Locate2u",
    "LogicHub SOAR",
    "Logsign SIEM",
    "Lumifi Cyber",
    "Lupin & Holmes",
    "Lynx Technology Partners",
    "MagicCube Security",
    "Managed Methods",
    "Mango Security",
    "Mantis Cybersecurity",
    "MATRIXX Software Security",
    "Mato Security",
    "MazeBolt DDoS",
    "MedCrypt",
    "Memcyco",
    "Menaya",
    "MetaCert",
    "Metallic Backup",
    "MicroFocus ArcSight",
    "MicroSec IoT",
    "Midnight Blue",
    "Minerva Labs EDR",
    "Mirach Security",
    "MixMode AI",
    "Mobix Communications",
    "Monokee Identity",
    "MorganFranklin",
    "Morpheus Data Security",
    "Motiv ICT Security",
    "Moxfive",
    "MWR InfoSecurity",
    "Myki Password Manager",
    "N-able RMM Security",
    "NAXSI WAF",
    "Nebulon",
    "Nessus Expert",
    "NetBrain Technologies",
    "NetCentrics",
    "Netcraft Anti-Phishing",
    "NetDiligence",
    "NetMotion",
    "Netrise Platform",
    "Netskope Private Access",
    "NeuShield",
    "Next DLP",
    "NextDLP Reveal",
    "NightDragon",
    "Nile Networking",
    "Nipper Firewall Auditor",
    "Noetic Cyber",
    "Normalyze DSPM",
    "NorthRow",
    "NotSoSecure",
    "NovaBACKUP",
    "NovaTech Automation",
    "Nucleon Cyber",
    "NuData Security",
    "NuHarbor Security",
    "Nuvolo Connected Workplace",
    "Nvisium Security",
    "NXLog",
    "Nyotron",
    "ObjectSecurity",
    "OctoXLabs",
    "Okera Data Access",
    "Oleria Identity",
    "OnDefend",
    "Ontic",
    "OpenBAS",
    "OpenDNS",
    "OpenID Foundation",
    "Opinnate",
    "OpSec Security",
    "Operative Intelligence",
    "Opsview Monitor",
    "Opticks",
    "Oracle Cloud Guard",
    "Oracle Data Safe",
    "Orca Runtime Security",
    "Orchestra Group",
    "Osirium PAM",
    "OTORIO Platform",
    "Outseer",
    "OwlGaze",
    "PacketFabric",
    "PacketTotal",
    "Paladin Cloud",
    "Palantir Foundry Security",
    "PaloAlto DNS Security",
    "Pandora FMS",
    "Panorama9",
    "Paraflare MDR",
    "Pathlock",
    "PatrOwl Security",
    "Penfield.AI",
    "Pensar Development",
    "Perch MDR",
    "Perforce Static Analysis",
    "PhishCloud",
    "PhishLine",
    "Phriendly Phishing",
    "Pistachio",
    "PlainID Authorization",
    "Polaris Infosec",
    "Polyverse",
    "PortDiver",
    "Postman API Security",
    "Preempt Security",
    "Prevalent AI",
    "Prey Device Management",
    "Prism Infosec",
    "Privacy Analytics",
    "PrivacyOps",
    "ProcessBolt AI Risk",
    "ProofID",
    "Protectimus",
    "Protexxa",
    "Pureport",
    "Qintel",
    "QomplX Risk",
    "Qualitia",
    "Quantum Xchange",
    "QuintessenceLabs",
    "Qwiet AI Security",
    "QWERX",
    "RAD Security",
    "RackTop Systems",
    "RackWare",
    "Radiflow OT Security",
    "Rank Software",
    "RankedRight",
    "RapidFire Tools",
    "RapidFort",
    "Raxis",
    "ReaQta XDR",
    "Reachability",
    "RealVNC",
    "Red Balloon Security",
    "Red Hat Advanced Cluster Security",
    "Red Sift OnDMARC",
    "Redacted",
    "Redscan",
    "Reflectiz",
    "Relyance AI",
    "Remediant PAM",
    "ReSec Technologies",
    "Resecurity Platform",
    "ResiliAnt",
    "Revelstoke SOAR",
    "RevBits",
    "Revision Legal",
    "Rewterz",
    "Rhino Security Labs",
    "Ribbon Security",
    "Ridgeback Network Defense",
    "Ripjar",
    "RiskOptics",
    "RiskSense",
    "RiskWatch",
    "Rivetz",
    "RocketCyber Platform",
    "Rockwell Collins Cyber",
    "RootSecure",
    "Root9B",
    "Rumble Network Discovery",
    "RunSafe Security",
    "Rutoken",
    "S1 Security",
    "S21sec Spain",
    "SAFECode",
    "SAINT Vulnerability Scanner",
    "Salus Security",
    "SAM Seamless Network",
    "Samurai Digital",
    "SandboxAQ",
    "SandFly Security",
    "Sangfor Technologies",
    "Saporo",
    "SaviyntIGA Platform",
    "Scalarr Mobile",
    "Scandit",
    "SciTokens",
    "Scout",
    "Scutum Cybersecurity",
    "Seal Security",
    "SecBI Autonomous XDR",
    "SecludIT",
    "Secnap CloudJacket",
    "SecPod SanerNow",
    "SecretHub",
    "SecureBridge",
    "SecureCircle",
    "SecureFlag Platform",
    "SecureLayer7",
    "SecurelyShare",
    "SecurEnds Identity",
    "Securiti Data Command Center",
    "SecurityAdvisorMe",
    "SecurityIntelligence",
    "SecurityJoes",
    "SEConion",
    "Sectigo CMS",
    "SeeMetrics",
    "Segugio",
    "SekurSafe",
    "Semmle LGTM",
    "SenCy Cyber",
    "Senhasegura PAM",
    "SenRa IoT",
    "Sepio Systems",
    "ServerScan",
    "Seventy2 Cybersecurity",
    "Shadow Security",
    "ShieldIO",
    "Shorepoint",
    "Silobreaker Intelligence",
    "SilverBullet",
    "SilverSky MSSP",
    "SimpleLogin",
    "SirenJack",
    "SiteLock Website Security",
    "SlashID Identity",
    "SlashNext AI",
    "Sliide Security",
    "SmartHive",
    "Smokescreen Deception",
    "SnapAttack",
    "Snoopwall",
    "SOC Prime Platform",
    "SOCAutomation",
    "Solana Security",
    "SonicWall Capture ATP",
    "SonicWall SecureFirst",
    "Sophos XDR",
    "SourceClear SCA",
    "SparkCognition",
    "Spec Security",
    "Specops Software",
    "SpiderSilk",
    "Spirent Communications",
    "SpireSec",
    "Splunk Attack Analyzer",
    "SpotBugs SAST",
    "Spyderbat Runtime",
    "StackAware",
    "StealthBits",
    "Sternum IoT Security",
    "StoneFly DR365",
    "Stormforge",
    "Strongbox IT Security",
    "Styra OPA",
    "Sudo Security Group",
    "SurfControl",
    "Swarmnetics",
    "Swimlane Turbine",
    "SynerComm",
    "Synopsys SIG",
    "Synthrone",
    "Sysdig Monitor",
    "SysTools Forensics",
    "Taegis XDR Platform",
    "Tamnoon Cloud",
    "TealTech",
    "TeleCommunity",
    "Tenable Attack Surface",
    "Teramind DLP",
    "Tessera Security",
    "Tetrate Service Bridge",
    "Thirdwave Solutions",
    "ThisIsMe Identity",
    "Thinkst Canary",
    "ThreatAdvice",
    "ThreatCast",
    "ThreatHunter.ai",
    "ThreatKey",
    "ThreatLocker Ringfencing",
    "ThreatSpike Labs",
    "ThreatWar",
    "Titaniam Encryption",
    "TinfoilMe",
    "TippingPoint IPS",
    "Todyl SASE Platform",
    "Tonic.ai Privacy",
    "TraceLink",
    "Traced Mobile",
    "TraceSecurity",
    "TrelliWare",
    "Trellix XDR Platform",
    "Trend Micro TippingPoint",
    "TriageSec",
    "Trident Information Security",
    "Trinity Cyber",
    "TruNarrative",
    "TrustLogix",
    "Trustworthy AI",
    "Turbine Labs",
    "TuringSense",
    "Tychon Endpoint",
    "Ubiqu Identity",
    "UberAgent",
    "Uila Application",
    "UKCloud",
    "UncommonX",
    "Unico Identity",
    "Unified Security",
    "UnifyID",
    "Uniqkey Business",
    "Untangle NG Firewall",
    "Ursa Major",
    "Usercube IAM",
    "V-Key",
    "Valiant TMS",
    "Valtix Cloud Firewall",
    "Variti Anti-DDoS",
    "VectorShield",
    "Venation",
    "Vera Security Platform",
    "VeraCrypt",
    "Vercara DNS Security",
    "Verimatrix",
    "Verified Identity",
    "Verodin BAS",
    "Versa Director",
    "VersaONE",
    "Veza Identity Security",
    "Viavi Solutions Network",
    "Vigilante Dark Web",
    "Vinculum Group",
    "Vipre Business",
    "Virsec Systems",
    "Virtana Infrastructure",
    "VisibleRisk Platform",
    "Vistara IT",
    "Vivint Smart Home Security",
    "Voxility CDN",
    "VulnCheck Intelligence",
    "Vulners DB",
    "Warden Security",
    "WatchTowr Platform",
    "WebPurify",
    "Whitecryption",
    "WhiteHat Security",
    "Whitebox Security",
    "Widevine DRM",
    "WiseSec",
    "WitFoo Precinct",
    "Wordfence WordPress",
    "Xebia Security",
    "Xperi",
    "Xtreme Security",
    "Yandex Security",
    "Yotascale Cloud",
    "Zapata Computing",
    "ZecOps Mobile",
    "Zenoss Platform",
    "ZeroHack",
    "ZeroTrust Guard",
    "Zinc Security",
    "Zivver Email",
    "ZKX Security",
    "Zonefox Insider",
    "ZPE Cloud",
    "Zyston MSSP",

    # ===== More niche/regional cybersecurity companies =====
    # Japanese cybersecurity
    "Trend Micro Japan",
    "NTT Security Holdings",
    "Macnica",
    "LAC Co",
    "SecureWorks Japan",
    "CyberDefense Institute",
    "Internet Initiative Japan",
    "NEC Cybersecurity",
    "Hitachi Security",
    "Toshiba Security",
    "JPCERT",
    "Soliton Systems",

    # Korean cybersecurity
    "AhnLab",
    "Penta Security",
    "Wins",
    "Secui",
    "Igloo Security Korea",
    "NSHC",
    "Genians",
    "MonitorApp",
    "Fasoo",
    "SGA Solutions",
    "STCLab",

    # Australian cybersecurity
    "CyberCX",
    "Tesserent",
    "Penten",
    "Kasada",
    "UpGuard",
    "Bugcrowd",
    "Airlock Digital",
    "Huntsman Security",
    "ParaFlare",
    "InfoTrust",
    "Sekuro",
    "Cydarm",
    "Internet 2.0",
    "Dvuln",

    # Singapore cybersecurity
    "Ensign InfoSecurity",
    "Group-IB Singapore",
    "Horangi Cyber Security",
    "Acronis Singapore",
    "Verizon Cyber Singapore",
    "ST Engineering Cybersecurity",

    # More Latin American cybersecurity
    "Tempest Security",
    "Morphus",
    "CLM",
    "Neoway",
    "Apura",
    "Cipher MSSP",
    "EXA Infosecurity",
    "Metabase Q",
    "Delta Protect",
    "Telmex Security",

    # Canadian cybersecurity
    "BlackBerry",
    "Magnet Forensics",
    "GoSecure",
    "eSentire",
    "Field Effect",
    "Calian Group",
    "Difenda",
    "Above Security",
    "Herjavec Group",
    "Trend Micro Canada",
    "CIRA DNS Firewall",
    "Beauceron",
    "Cycura",
    "Cybrosys Technologies",

    # Middle East cybersecurity (non-Israeli)
    "DarkMatter",
    "HelpAG",
    "Spire Solutions",
    "Paramount Computer Systems",
    "StarLink",
    "GBM",
    "Mindware",
    "CPX",
    "Injazat",
    "Cloud Box Technologies",
    "VIRTUS Interpress",
    "Edvance Technology",

    # African cybersecurity
    "Serianu",
    "Liquid Intelligent Technologies",
    "Dimension Data",
    "Internet Solutions",
    "Purple Group",
    "Wolfpack Information Risk",

    # More open source security tools
    "ModSecurity",
    "Fail2Ban",
    "CrowdSec Community",
    "Tripwire Open Source",
    "AIDE",
    "rkhunter",
    "chkrootkit",
    "Tiger",
    "Samhain",
    "Auditd",
    "SELinux",
    "AppArmor",
    "Tomoyo Linux",
    "grsecurity",
    "PaX",
    "Firejail",
    "Bubblewrap",
    "nftables",
    "iptables",
    "ufw",
    "Shorewall",
    "fwknop",
    "PortSentry",
    "DenyHosts",
    "SSHGuard",
    "Logwatch",
    "Logcheck",
    "PSAD",
    "Fwlogwatch",
    "Sagan",
    "Prelude SIEM",
    "ELSA",
    "Balabit",
    "syslog-ng",
    "rsyslog",
    "Graylog",
    "Fluentd",
    "Fluent Bit",
    "Vector.dev",
    "Loki",
    "Promtail",
    "Filebeat",
    "Winlogbeat",
    "Auditbeat",
    "Packetbeat",
    "Heartbeat",
    "Metricbeat",
    "Functionbeat",
    "Journalbeat",

    # More cloud-native security
    "Aqua Trivy",
    "Docker Scout",
    "Snyk Container",
    "JFrog Container Security",
    "Red Hat Quay",
    "Harbor Registry",
    "Notary",
    "Cosign",
    "Rekor",
    "Fulcio",
    "Sigstore",
    "in-toto",
    "TUF",
    "SPIFFE",
    "SPIRE",
    "Istio",
    "Linkerd",
    "Consul Connect",
    "Open Policy Agent",
    "Kyverno",
    "Kubewarden",
    "Polaris",
    "Starboard",
    "Veinmind",
    "Cloud Custodian",
    "Prowler",
    "ScoutSuite",
    "CloudMapper",
    "Cartography",
    "CloudSploit",
    "S3Scanner",
    "PMapper",
    "Pacu",
    "Endgame",
    "Cloudfox",
    "Steampipe",
    "CloudQuery",

    # More DevSecOps tools
    "Talisman",
    "git-secrets",
    "detect-secrets",
    "whispers",
    "repo-supervisor",
    "credential-digger",
    "ggshield",
    "secretlint",
    "skjold",
    "safety",
    "pip-audit",
    "npm audit",
    "yarn audit",
    "cargo audit",
    "govulncheck",
    "nancy",
    "bundler-audit",
    "retire.js",
    "auditjs",
    "is-website-vulnerable",
    "Renovate",
    "Dependabot",
    "Snyk Advisor",
    "Socket.dev",
    "Deps.dev",
    "OSV Scanner",
    "Grype",
    "Syft",
    "CycloneDX",
    "SPDX",
    "OWASP CycloneDX",

    # Additional IAM / Identity
    "Keycloak",
    "FreeIPA",
    "OpenLDAP",
    "389 Directory Server",
    "Gluu Server",
    "WSO2 Identity Server",
    "Apereo CAS",
    "Shibboleth",
    "SimpleSAMLphp",
    "Authentik",
    "Authelia",
    "Zitadel",
    "Ory",
    "Casdoor",
    "Logto",
    "SuperTokens",
    "FusionAuth",
    "LoginRadius",

    # More vulnerability scanners
    "Wapiti",
    "Arachni",
    "Skipfish",
    "Grabber",
    "Vega Scanner",
    "IronWASP",
    "Cenzic",
    "Rapid7 AppSpider",
    "WhiteHat Sentinel",
    "NetSparker",
    "Bright Security",
    "NeuraLegion",
    "Detectify",
    "Intruder.io",
    "Pentest-Tools",
    "Crashtest Security",
    "ImmuniWeb",
    "Breachlock",

    # Hardware security modules
    "Thales Luna HSM",
    "Utimaco HSM",
    "Entrust nShield",
    "Futurex KMES",
    "AWS CloudHSM",
    "Azure Dedicated HSM",
    "Google Cloud HSM",
    "Fortanix DSM",
    "Securosys Primus",
    "Atos Trustway",
    "Cavium LiquidSecurity",
    "IBM Z Crypto Express",

    # More email/DNS security
    "DMARC Analyzer",
    "Valimail DMARC",
    "dmarcian",
    "EasyDMARC",
    "PowerDMARC",
    "Red Sift OnDMARC",
    "Agari",
    "ProofPoint DMARC",
    "Mimecast DMARC",
    "URIports",
    "MailChannels",

    # More WAF / Bot solutions
    "Reblaze",
    "Prophaze",
    "AppTrana WAF",
    "Indusface AppTrana",
    "StackPath WAF",
    "Sucuri WAF",
    "Wordfence WAF",
    "NinjaFirewall",
    "BitNinja WAF",
    "Wallarm WAAP",
    "ThreatX WAF",
    "Cequence Bot Defense",
    "Kasada Bot Defense",
    "DataDome Bot Protection",
    "Shape Security (F5)",

    # Endpoint management
    "Fleet Device Management",
    "Kolide",
    "Addigy",
    "Mosyle Business",
    "SimpleMDM",
    "Kandji",
    "Jamf Pro",
    "Hexnode UEM",
    "ManageEngine Endpoint Central",
    "Microsoft Intune",
    "VMware Workspace ONE",
    "Ivanti Neurons for UEM",
    "SOTI MobiControl",
    "Cisco Meraki MDM",
    "BlackBerry UEM",
    "Citrix Endpoint Management",
    "Matrix42",
    "Baramundi",
    "FileWave",
    "Miradore",
    "Snow Software",

    # Governance Risk Compliance (more)
    "Archer GRC",
    "MetricStream GRC",
    "SAI360 GRC",
    "Diligent GRC",
    "Navex Global GRC",
    "Riskonnect GRC",
    "Galvanize GRC",
    "ProcessUnity GRC",
    "Resolver GRC",
    "Corporater GRC",
    "ISMS.online GRC",
    "Eramba",
    "SimpleRisk",
    "OpenGRC",
    "Cimcor CimTrak",
    "NNT Change Tracker",
    "Tripwire Enterprise",
    "Qualys Policy Compliance",
    "Nessus Compliance",
    "CIS-CAT",
    "SCC (SCAP Compliance Checker)",
    "OpenSCAP",

    # Security analytics
    "Securonix",
    "LogRhythm NDR",
    "Devo Security Analytics",
    "Hunters SOC Platform",
    "Google Chronicle SecOps",
    "Microsoft Sentinel Analytics",
    "Anvilogic",
    "CardinalOps Detection",
    "SOC Prime DeTT&CT",
    "Sigma Rules",
    "YARA Rules",
    "Suricata Rules",
    "Snort Rules",
    "Elastic Detection Rules",

    # More risk quantification
    "FAIR Institute",
    "RiskLens Platform",
    "Safe Security FAIR",
    "Kovrr Cyber Risk",
    "Axio360",
    "CyberStrong",
    "Balbix",
    "Tenable Lumin",
    "Kenna Security VM",
    "Cisco Kenna",

    # Additional companies from various sources
    "A10 Networks Thunder",
    "Adallom (Microsoft)",
    "Agari Data",
    "Agiliance RiskVision",
    "Ahope Security",
    "AISEC",
    "Akamai Identity Cloud",
    "Akamai Page Integrity",
    "Alcide (Rapid7)",
    "AlgoSec Fireflow",
    "AlienVault USM Anywhere",
    "Allure Security Technology",
    "Amberflo Security",
    "Anchore Enterprise",
    "Anomali ThreatStream",
    "Aperture Data Studio",
    "AppGate SDP",
    "AppSec Labs",
    "AppSecEngineer",
    "Arete Incident Response",
    "Armorblox (Cisco)",
    "ArmorCode ASPM",
    "AST Security",
    "AuthN by IDEE",
    "BalaBit (One Identity)",
    "Banyan Cloud",
    "Barracuda PhishLine",
    "BastionZero",
    "Bay Dynamics Risk",
    "Bedrock Security",
    "BeyondID",
    "Black Lantern Security",
    "Blink Ops",
    "BlockAPT",
    "Blue Team Alpha",
    "BMC Helix Discovery",
    "Boole Server",
    "BreachLock Inc",
    "Bugsnag",
    "C3 AI Cybersecurity",
    "Canary Tokens",
    "Caveonix",
    "Censinet Risk",
    "Cerberus Sentinel",
    "Certes Networks",
    "Cider Security (Palo Alto)",
    "Cog Systems",
    "ComplyCloud Platform",
    "Corellium",
    "Cortex Data Lake",
    "Crypto Quantique",
    "CryptoStopper Ransomware",
    "CyberArk Identity Security",
    "CyberArk Labs",
    "Cybellum Device Security",
    "CyberSponse (Fortinet)",
    "Cycurio",
    "Dashlane Business",
    "DataVisor Platform",
    "Dataminr",

    # ===== Final batch to surpass 5000 =====
    # More security products and branded solutions
    "Microsoft Defender for Office 365",
    "Microsoft Defender for Cloud Apps",
    "Microsoft Defender for Identity",
    "Microsoft Defender for Endpoint",
    "Microsoft Defender for IoT",
    "Microsoft Purview Compliance",
    "Microsoft Purview Information Protection",
    "Microsoft Purview Data Loss Prevention",
    "Microsoft Purview Insider Risk",
    "Microsoft Entra Permissions Management",
    "Microsoft Entra Verified ID",
    "Microsoft Entra Workload Identities",
    "Microsoft Intune Endpoint Protection",
    "Microsoft Sentinel",
    "Microsoft Copilot for Security",
    "AWS Security Hub",
    "AWS GuardDuty",
    "AWS Inspector",
    "AWS Macie",
    "AWS Detective",
    "AWS IAM Identity Center",
    "AWS CloudTrail",
    "AWS Config",
    "AWS Firewall Manager",
    "AWS Network Firewall",
    "AWS WAF",
    "AWS Shield Advanced",
    "AWS Secrets Manager",
    "AWS Certificate Manager",
    "AWS KMS",
    "AWS CloudHSM",
    "AWS Artifact",
    "AWS Audit Manager",
    "AWS Control Tower",
    "AWS Organizations",
    "AWS RAM",
    "AWS SSO",
    "AWS STS",
    "AWS IoT Device Defender",
    "AWS Verified Access",
    "Google Cloud Armor",
    "Google Cloud IAP",
    "Google Cloud DLP",
    "Google BeyondCorp Enterprise",
    "Google Cloud Asset Inventory",
    "Google Cloud Binary Authorization",
    "Google Cloud Certificate Authority",
    "Google VPC Service Controls",
    "Google Assured Workloads",
    "Google Cloud Security Scanner",
    "Google reCAPTCHA Enterprise",
    "Google Mandiant Attack Surface Management",
    "Google Mandiant Digital Threat Monitoring",
    "Google Mandiant Breach Analytics",
    "Google Mandiant Threat Intelligence",
    "Google Chronicle SOAR",
    "Google Threat Intelligence",
    "Google Workspace Security",
    "Google Safe Browsing",
    "Azure Security Center",
    "Azure Sentinel",
    "Azure Firewall",
    "Azure DDoS Protection",
    "Azure Key Vault",
    "Azure Information Protection",
    "Azure Confidential Computing",
    "Azure Bastion",
    "Azure Private Link",
    "Azure Front Door WAF",
    "Azure Active Directory",
    "Azure AD B2C",
    "Azure DevOps Security",

    # Palo Alto Networks products
    "Palo Alto Cortex XDR",
    "Palo Alto Cortex XSOAR",
    "Palo Alto Cortex Xpanse",
    "Palo Alto Prisma Cloud",
    "Palo Alto Prisma Access",
    "Palo Alto Prisma SASE",
    "Palo Alto WildFire",
    "Palo Alto GlobalProtect",
    "Palo Alto Panorama",
    "Palo Alto VM-Series",
    "Palo Alto CN-Series",
    "Palo Alto IoT Security",
    "Palo Alto DNS Security",
    "Palo Alto URL Filtering",
    "Palo Alto Threat Prevention",
    "Palo Alto Advanced Threat Prevention",
    "Palo Alto Advanced URL Filtering",
    "Palo Alto SaaS Security",
    "Palo Alto Enterprise DLP",

    # Fortinet products
    "Fortinet FortiGate",
    "Fortinet FortiManager",
    "Fortinet FortiAnalyzer",
    "Fortinet FortiSandbox",
    "Fortinet FortiMail",
    "Fortinet FortiWeb",
    "Fortinet FortiADC",
    "Fortinet FortiDDoS",
    "Fortinet FortiDeceptor",
    "Fortinet FortiToken",
    "Fortinet FortiAuthenticator",
    "Fortinet FortiNAC",
    "Fortinet FortiCASB",
    "Fortinet FortiGuard",
    "Fortinet FortiSwitch",
    "Fortinet FortiAP",
    "Fortinet FortiExtender",
    "Fortinet FortiMonitor",
    "Fortinet FortiTester",
    "Fortinet FortiRecon",
    "Fortinet FortiDevSec",
    "Fortinet FortiCNP",
    "Fortinet FortiPAM",

    # CrowdStrike products
    "CrowdStrike Falcon Prevent",
    "CrowdStrike Falcon Insight",
    "CrowdStrike Falcon OverWatch",
    "CrowdStrike Falcon Discover",
    "CrowdStrike Falcon Spotlight",
    "CrowdStrike Falcon FileVantage",
    "CrowdStrike Falcon LogScale",
    "CrowdStrike Falcon Horizon",
    "CrowdStrike Falcon Surface",
    "CrowdStrike Falcon Identity",
    "CrowdStrike Falcon Data Protection",
    "CrowdStrike Charlotte AI",

    # Cisco security products
    "Cisco Umbrella",
    "Cisco Secure Firewall",
    "Cisco Secure Endpoint",
    "Cisco Secure Email",
    "Cisco Secure Access",
    "Cisco Secure Workload",
    "Cisco Secure Network Analytics",
    "Cisco Secure Client",
    "Cisco Duo Security",
    "Cisco Talos Intelligence",
    "Cisco ThousandEyes",
    "Cisco Meraki MX Security",
    "Cisco ISE",
    "Cisco Identity Services Engine",
    "Cisco AMP",
    "Cisco SecureX Platform",
    "Cisco Hypershield",

    # IBM Security products
    "IBM QRadar SIEM",
    "IBM QRadar SOAR",
    "IBM Guardium",
    "IBM Verify",
    "IBM MaaS360",
    "IBM X-Force Threat Intelligence",
    "IBM Cloud Pak for Security",
    "IBM Randori",
    "IBM ReaQta",
    "IBM Trusteer",
    "IBM Security Discover and Classify",

    # Zscaler products
    "Zscaler Internet Access",
    "Zscaler Private Access",
    "Zscaler Digital Experience",
    "Zscaler Data Protection",
    "Zscaler Deception",
    "Zscaler Cloud Browser Isolation",
    "Zscaler Workload Communications",
    "Zscaler Risk360",

    # More standalone cybersecurity companies
    "Abnormal Security Platform",
    "ActZero",
    "Aembit Workload IAM",
    "Agilicus",
    "AgileBlue",
    "Ahope Security",
    "AISEC",
    "AlienApp",
    "Altitude Networks",
    "Ambient.ai Security",
    "Anetac Identity",
    "Ansys medini analyze",
    "Anubis Networks",
    "Anvil Secure",
    "Apex Technology Services",
    "Apicurio Registry",
    "Aplite Security",
    "AppSec Phoenix",
    "Archon Secure",
    "AST Security Group",
    "Atsign",
    "Avalor Security",
    "Avetta Risk",
    "Banshee Security",
    "Barracuda SecureEdge",
    "Blue Mantis",
    "Blue Ridge Networks",
    "Bromium (HP)",
    "BugSec Group",
    "BullWall Ransomware",
    "C1 Risk Platform",
    "CACI International Cyber",
    "Cerby Identity Platform",
    "CheckRed SSPM",
    "CipherTrust Manager",
    "Cisco Stealthwatch",
    "Cisco Tetration",
    "Citadel Information Group",
    "CloudKnox Security",
    "CoalFire Labs",
    "Codelock Security",
    "Cognito AI Security",
    "CoSoSys Endpoint Protector",
    "CyberArk Dynamic Privileged Access",
    "CyberArk Secrets Hub",
    "CyberArk Endpoint Privilege Manager",
    "CyberArk Secure Browser",
    "CyberGRX Exchange",
    "Cyderes Platform",
    "Cyolo Secure Access",
    "DarkMatter Group",
    "Dataprise MSP",
    "Delta Protect",
    "Devo Security Operations",
    "Dragos Platform",
    "Duo Beyond",
    "Duo Passport",
    "Duo Trust Monitor",
    "Eclypsium Firmware Security",
    "Eden Data Compliance",
    "Edvance Technology",
    "Elastio Recovery",
    "Enclave Networks",
    "Endor Labs Dependency",
    "Entro Secrets Security",
    "Exein Runtime",
    "Exium SASE",
    "Expanse (Cortex)",
    "Eye Security Insurance",
    "Flare.io Dark Web",
    "FlexibleIR Response",
    "Fortanix Confidential Computing",
    "Galvanick OT",
    "Gem Cloud Detection",
    "Gradient Cyber MDR",
    "Graphus Automated Phishing",
    "Guardknox Automotive",
    "Guardz SMB Security",
    "GreenPages Cloud",
    "Hackuity Vulnerability Priority",
    "HarfangLab EDR",
    "HelpSystems (Fortra)",
    "HighGround Cyber",
    "Horangi Cloud Security",
    "Hub Security Confidential",
    "Hypr Passwordless",
    "IONIX Attack Surface",
    "IronWASP Scanner",
    "JupiterOne CAASM",
    "KnowBe4 PhishER",
    "KnowBe4 SecurityCoach",
    "Konfidas Consulting",
    "LAC Cyber Japan",
    "LayerX Browser Security",
    "LevelBlue MDR",
    "Lightspin CNAPP",
    "Lumifi MDR",
    "Macnica Networks",
    "Mammoth Cyber Browser",
    "Mesh Security (Ermetic)",
    "Metabase Q Mexico",
    "Miggo ADR",
    "MITRE Engenuity ATT&CK",
    "Mnemonic Norway",
    "NetFoundry Zero Trust",
    "Netography Network Defense",
    "Nightfall DLP Cloud",
    "Noetic CAASM",
    "NuHarbor Security MSSP",
    "Ontic Safety Intelligence",
    "OpenBAS Breach Simulation",
    "OpenZiti Network",
    "Operant AI Runtime",
    "Oort Identity Threat",
    "Osano Privacy Platform",
    "Outflank Red Team",
    "Paladin Cloud Governance",
    "Panorays TPRM Platform",
    "ParaFlare SOC",
    "Pathlock GRC",
    "Penta Security WAPPLES",
    "Phylum Supply Chain",
    "Pistachio Awareness",
    "Plurilock CloudCodes",
    "ProcessBolt TPRM",
    "ProjectDiscovery Nuclei",
    "Proton Pass",
    "Proton Drive",
    "Proton Mail",
    "Push Security Browser",
    "Qintel Intelligence",
    "Rapid7 MDR",
    "Rapid7 InsightIDR SIEM",
    "Rapid7 InsightVM Vulnerability",
    "Rapid7 InsightConnect SOAR",
    "Rapid7 InsightAppSec DAST",
    "Red Canary MDR Platform",
    "Red Access Browser",
    "RevealSecurity ITDR",
    "Rezonate Access Platform",
    "RiskOptics ROAR",
    "Riot Security Awareness",
    "Rivetz Trusted Execution",
    "S21sec European MSSP",
    "Sangfor Cyber Command",
    "Sekoia XDR",
    "Sekuro Australian MSSP",
    "SentinelOne Purple AI",
    "SentinelOne Ranger",
    "Skyhawk Security CNDR",
    "SlashNext Phishing Defense",
    "Snowbit MDR",
    "SOCFortress SIEM",
    "SOCSoter Platform",
    "Soliton Systems Japan",
    "SOOS SCA",
    "SpearTip Incident Response",
    "Spin Technology SSPM",
    "Stairwell Inception",
    "StepSecurity Harden Runner",
    "Stratejm MDR Canada",
    "Stream Security Cloud",
    "StrikeReady SOC",
    "SURF Security Browser",
    "Sweet Security Cloud Native",
    "Sygnia Consulting",
    "T-Systems Cybersecurity",
    "TechDemocracy MSSP",
    "Telmex Security Mexico",
    "Tempest Security Brazil",
    "Thinkst Canary Tokens",
    "ThreatNG Digital Risk",
    "Titaniam Vault",
    "Todyl Partner Platform",
    "Trinity Cyber ISP",
    "TrustCloud Compliance",
    "TrustLogix Data Access",
    "Tuskira Security",
    "Upwind Cloud Security",
    "Vali Cyber Linux EDR",
    "Veriti Security Platform",
    "Vicarius vRx Vulnerability",
    "Vijilan Security SOC",
    "VulnCheck Exploit Intelligence",
    "Wabbi SDLC Security",
    "WatchTowr Offensive",
    "Wing Security SaaS",
    "WiJungle India",
    "Xage Security OT",
    "Xplain Data",
    "YesWeHack Europe",
    "Yogosha VDP Europe",
    "Zafran Mitigation Platform",
    "Zenity AI Security",
    "ZeroFox Digital Risk",
    "ZeroTier Networking",
    "Zilla Security Access",
    "Zimperium Mobile Defense",
    "Zivver Secure Email",
    "Zluri SaaS Management",
    "Zscaler Posture Control",

    # Final stragglers
    "Abnormal ICES",
    "Clearwater Security",
    "Digital Shadows",
    "Mandiant Advantage Platform",
    "NetWitness Platform",
    "RSA NetWitness",
    "RSA Archer GRC",
    "RSA SecurID Access",
    "RSA Fraud & Risk Intelligence",
    "SonicWall Network Security",
    "SonicWall Email Security",
    "SonicWall Cloud App Security",
    "SonicWall Capture Client",
    "SonicWall Access Security",
    "Sophos Central Admin",
    "Sophos Firewall",
    "Sophos Intercept X",
    "Sophos Cloud Optix",
    "Sophos Email",
    "Sophos Mobile",
    "Sophos Phish Threat",
    "Sophos MDR Complete",
    "Sophos ZTNA",
    "Sophos Switch",
    "Sophos AP",
    "Sophos DNS Protection",
    "Trend Micro Deep Security",
    "Trend Micro Cloud One Workload",
    "Trend Micro Cloud One Conformity",
    "Trend Micro Cloud One Network",
    "Trend Micro Cloud One Container",
    "Trend Micro Cloud One File Storage",
    "Trend Micro Apex One",
    "Trend Micro Vision One XDR",
    "Trend Micro Email Security",
    "Trend Micro Web Security",
    "Trend Micro Network One",
    "Kaspersky Endpoint Security Cloud",
    "Kaspersky Small Office Security",
    "Kaspersky Total Security",
    "Kaspersky Anti-Targeted Attack",
    "Kaspersky EDR Optimum",
    "Kaspersky MDR",
    "Kaspersky Threat Intelligence",
    "Kaspersky Industrial CyberSecurity",
    "ESET PROTECT Entry",
    "ESET PROTECT Advanced",
    "ESET PROTECT Complete",
    "ESET PROTECT Enterprise",
    "ESET Inspect",
    "ESET LiveGuard Advanced",
    "ESET Secure Authentication",
    "ESET Endpoint Encryption",
    "Bitdefender GravityZone Ultra",
    "Bitdefender GravityZone Cloud",
    "Bitdefender MDR",
    "Bitdefender XDR",
    "Bitdefender GravityZone CSPM",
    "Bitdefender Integrity Monitoring",
    "WatchGuard FireboxV",
    "WatchGuard AuthPoint",
    "WatchGuard ThreatSync",
    "WatchGuard Cloud",
    "WatchGuard Endpoint Security",
    "WatchGuard DNSWatchGO",
    "WatchGuard Network Security",
    "Barracuda Total Email Protection",
    "Barracuda CloudGen WAN",
    "Barracuda WAF-as-a-Service",
    "Barracuda Backup",
    "Barracuda Data Inspector",
    "Barracuda Cloud Security Guardian",
    "Barracuda XDR",
    "F5 BIG-IP ASM",
    "F5 BIG-IP APM",
    "F5 BIG-IP DNS",
    "F5 BIG-IP AFM",
    "F5 NGINX App Protect",
    "F5 Distributed Cloud WAF",
    "F5 Distributed Cloud Bot Defense",
    "F5 Distributed Cloud DDoS",
    "F5 Silverline WAF",
    "F5 Silverline DDoS",
    "Akamai Guardicore Segmentation",
    "Akamai Enterprise Threat Protector",
    "Akamai Identity Cloud",
    "Akamai Page Integrity Manager",
    "Akamai API Gateway",
    "Akamai Client-Side Protection",
    "Akamai Secure Internet Access",
    "Akamai MFA",
    "Akamai Hunt",
    "Check Point Harmony Endpoint",
    "Check Point Harmony Email",
    "Check Point Harmony Browse",
    "Check Point Harmony Connect",
    "Check Point Harmony Mobile",
    "Check Point CloudGuard CNAPP",
    "Check Point CloudGuard WAF",
    "Check Point Infinity SOC",
    "Check Point ThreatCloud",
    "Check Point VSX",
    "Check Point Maestro",
    "Check Point SASE",
]
